//! Announcements to the user (ADR-0006).
//!
//! Every state change is announced through an [`Announcer`]. Frontends pick
//! the implementation:
//!
//! - [`SpeechAnnouncer`]: self-voicing, through the speech service (wired by
//!   the app with a closure, so this crate does not depend on speech);
//! - [`StatusLineAnnouncer`]: the terminal's status line, which terminal
//!   screen readers read as it changes;
//! - [`LogAnnouncer`]: records every announcement, for tests;
//! - [`RingAnnouncer`]: keeps only the latest 256, for a long-running
//!   reader (the terminal frontend);
//! - [`MultiAnnouncer`]: several of the above at once;
//! - [`Shared`]: a clonable handle, so the app can own an announcer while
//!   the TUI draws the status line from it and tests read the log;
//! - the GUI's live-region announcer, which lives in `textweaver-xilem`
//!   (ADR-0027); the `live-region` feature here is reserved for it.
//!
//! The [`Announcement`] catalog gives some state changes fixed wording, a
//! [`Priority`], and a text for each [`Verbosity`] level; the application
//! words most of its messages itself (see `textweaver-app`) and sends them
//! through the same announcer and verbosity filter. Frontends call
//! [`Announcer::announce_event`] with the user's verbosity. star announced
//! some changes only on the status bar (rate, Speech Cursor, edit mode,
//! resume position) and gave no feedback at all for a TUI pause;
//! textweaver announces all of them.
//!
//! # Verbosity levels
//!
//! - **Low**: only what the user cannot otherwise know: errors, the result
//!   of a command that did not move or read anything ("No next heading",
//!   "No matches for cell"), values the user just changed, and mode
//!   changes. Short forms ("285", "3 of 7").
//! - **Normal** (default): adds structure names ("Heading level 2,
//!   Methods", "Table with 3 rows and 4 columns"), playback state (paused,
//!   stopped), and fuller wording ("Rate 285 words per minute").
//! - **High**: adds positions and counts (history position, line totals,
//!   the saved date), "Reading at 265 words per minute" when reading
//!   starts, and key hints.
//!
//! Anything said at one level is also said at every level above it (a
//! test). Wording avoids symbols a speech engine would skip or spell out.
//!
//! # Screen readers
//!
//! [`AccessMode`] (`[accessibility] mode`) decides, with [`route`], whether
//! each kind of output ([`Channel`]) is spoken, shown on the status line, or
//! both, so nothing is heard twice when a screen reader reads the status
//! line: self-voicing, screen-reader, or hybrid (see [`mode`]).
//! [`detect::detect`] tells whether a screen reader is running.
//!
//! # Verbosity table
//!
//! Generated by [`verbosity_table`] and checked by a test; "—" means
//! nothing is said.
//!
//! <!-- VERBOSITY-TABLE-START -->
//! | Kind | Priority | Low | Normal | High |
//! |---|---|---|---|---|
//! | `playing` | assertive | — | — | Reading at 265 words per minute |
//! | `paused` | assertive | — | Paused | Paused |
//! | `resumed` | assertive | — | — | Resuming |
//! | `stopped` | assertive | — | Stopped | Stopped |
//! | `finished_reading` | polite | — | End of document | End of document |
//! | `rate` | assertive | 285 | Rate 285 words per minute | Rate 285 words per minute |
//! | `pitch` | assertive | Pitch minus 2 | Pitch minus 2 | Pitch minus 2 |
//! | `volume` | assertive | 80 percent | Volume 80 percent | Volume 80 percent |
//! | `speed_preset` | assertive | study | Preset study, 200 words per minute | Preset study, 200 words per minute |
//! | `voice` | assertive | Voice Reed | Voice Reed | Voice Reed |
//! | `opened` | polite | Notes | Opened Notes | Opened Notes |
//! | `open_failed` | assertive | Could not open essay.docx: the file is damaged | Could not open essay.docx: the file is damaged | Could not open essay.docx: the file is damaged |
//! | `resumed_at` | polite | — | Resumed at 42 percent | Resumed at 42 percent, saved 2026-09-25 |
//! | `position_cleared` | assertive | Reading position cleared | Reading position cleared | Reading position cleared |
//! | `heading` | polite | Methods | Heading level 2, Methods | Heading level 2, Methods |
//! | `table` | polite | Table | Table with 3 rows and 4 columns | Table with 3 rows and 4 columns |
//! | `list` | polite | List | List with 5 items | List with 5 items |
//! | `link` | polite | home page | Link, home page | Link, home page |
//! | `no_next` | assertive | No next heading | No next heading | No next heading |
//! | `no_previous` | assertive | No previous table | No previous table | No previous table |
//! | `start_of_document` | assertive | Start of document | Start of document | Start of document |
//! | `end_of_document` | assertive | End of document | End of document | End of document |
//! | `blank_line` | assertive | blank | blank | blank |
//! | `position` | assertive | Line 12, 4 percent | Line 12, 4 percent, in Introduction | Line 12 of 300, 4 percent, in Introduction |
//! | `history` | assertive | — | — | History position 3 of 5 |
//! | `history_present` | assertive | — | Back at the present position | Back at the present position |
//! | `no_history` | assertive | No earlier history | No earlier history | No earlier history |
//! | `speech_cursor` | assertive | Speech cursor on | Speech cursor on | Speech cursor on |
//! | `edit_mode` | assertive | Edit mode | Edit mode | Edit mode |
//! | `hint` | polite | — | — | Tab leaves Speech Cursor |
//! | `match` | assertive | 3 of 7 | Match 3 of 7 | Match 3 of 7 |
//! | `search_wrapped` | assertive | — | Search wrapped to the top | Search wrapped to the top |
//! | `no_matches` | assertive | No matches for cell | No matches for cell | No matches for cell |
//! | `bookmark_added` | assertive | Bookmark mark1 | Bookmark mark1 set at 42 percent | Bookmark mark1 set at 42 percent |
//! | `bookmark_reached` | assertive | Bookmark mark1 | Bookmark mark1 | Bookmark mark1 |
//! | `bookmark_deleted` | assertive | Bookmark mark1 deleted | Bookmark mark1 deleted | Bookmark mark1 deleted |
//! | `no_bookmarks` | assertive | No bookmarks | No bookmarks | No bookmarks |
//! | `note_added` | assertive | Note added | Note added at 42 percent | Note added at 42 percent |
//! | `highlight_added` | assertive | Highlighted | Highlighted in yellow | Highlighted in yellow |
//! | `note_reached` | assertive | Note: check this, on “claim” | Note: check this, on “claim” | Note: check this, on “claim” |
//! | `note_deleted` | assertive | Note deleted | Note deleted | Note deleted |
//! | `no_notes` | assertive | No notes or highlights | No notes or highlights | No notes or highlights |
//! | `library_folder_added` | assertive | Added Readings | Added folder Readings with 12 documents | Added folder Readings with 12 documents |
//! | `sync_merged` | polite | — | Merged 2 changes from another device | Merged 2 changes from another device |
//! | `new_document` | assertive | New document, ready for editing | New document, ready for editing | New document, ready for editing |
//! | `saved` | polite | Saved | Saved notes.md | Saved notes.md |
//! | `save_failed` | assertive | Could not save: the disk is full | Could not save: the disk is full | Could not save: the disk is full |
//! | `undo` | assertive | — | Undo | Undo |
//! | `redo` | assertive | — | Redo | Redo |
//! | `nothing_to_undo` | assertive | Nothing to undo | Nothing to undo | Nothing to undo |
//! | `format_needs_edit_mode` | assertive | Turn on edit mode to format text | Turn on edit mode to format text | Turn on edit mode to format text |
//! | `replaced` | assertive | Replaced 4 matches | Replaced 4 matches | Replaced 4 matches |
//! | `table_inserted` | assertive | Inserted a table with 2 rows and 3 columns | Inserted a table with 2 rows and 3 columns | Inserted a table with 2 rows and 3 columns |
//! | `image_inserted` | assertive | Inserted image pic.png | Inserted image pic.png | Inserted image pic.png |
//! | `recovered` | polite | Recovered unsaved work. Remember to save. | Recovered unsaved work. Remember to save. | Recovered unsaved work. Remember to save. |
//! | `theme` | assertive | Theme galaxy | Theme galaxy | Theme galaxy |
//! | `line_numbers` | assertive | Line numbers on | Line numbers on | Line numbers on |
//! | `character_keys` | assertive | Single-key shortcuts off | Single-key shortcuts off | Single-key shortcuts off |
//! | `error` | assertive | Speech engine stopped | Speech engine stopped | Speech engine stopped |
//! | `info` | polite | — | Copied | Copied |
//! <!-- VERBOSITY-TABLE-END -->
//!
//! Owner: Agent C.

use std::sync::{Arc, Mutex, MutexGuard};

use serde::{Deserialize, Serialize};
pub use textweaver_core::Verbosity;

mod announce;
pub mod detect;
pub mod level;
pub mod mode;

pub use announce::{Announcement, verbosity_table};
pub use level::{Importance, InterfaceLevel, lets_through};
pub use mode::{AccessMode, Channel, CursorPlacement, Route, RouteContext, SayAll, route};

/// How urgently an announcement should be delivered.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Priority {
    /// Wait for current speech to finish.
    #[default]
    Polite,
    /// Interrupt current announcements.
    Assertive,
}

/// Something that tells the user about a state change.
pub trait Announcer {
    /// Announces `text`.
    fn announce(&mut self, text: &str, priority: Priority);

    /// Announces `text` only when the user's verbosity is at least `min`.
    fn announce_at(&mut self, text: &str, priority: Priority, min: Verbosity, current: Verbosity) {
        if current >= min {
            self.announce(text, priority);
        }
    }

    /// Announces a catalog entry at the user's verbosity, with its own
    /// priority. Says nothing when the entry is silent at that level.
    fn announce_event(&mut self, event: &Announcement, verbosity: Verbosity) {
        if let Some(text) = event.text(verbosity) {
            self.announce(&text, event.priority());
        }
    }
}

impl<A: Announcer + ?Sized> Announcer for Box<A> {
    fn announce(&mut self, text: &str, priority: Priority) {
        (**self).announce(text, priority);
    }
}

/// Records every announcement; for tests and the scripted TUI test.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct LogAnnouncer {
    /// Everything announced, oldest first.
    pub log: Vec<(String, Priority)>,
}

impl LogAnnouncer {
    /// The announced texts, oldest first.
    pub fn texts(&self) -> Vec<&str> {
        self.log.iter().map(|(t, _)| t.as_str()).collect()
    }

    /// The most recent announcement.
    pub fn last(&self) -> Option<&str> {
        self.log.last().map(|(t, _)| t.as_str())
    }
}

impl Announcer for LogAnnouncer {
    fn announce(&mut self, text: &str, priority: Priority) {
        self.log.push((text.to_owned(), priority));
    }
}

/// Keeps only the most recent announcements, in a ring of fixed size: the
/// terminal reader's record of what was said, which must not grow for as
/// long as the reader runs ([`LogAnnouncer`] keeps everything, for tests).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RingAnnouncer {
    entries: std::collections::VecDeque<(String, Priority)>,
    capacity: usize,
}

impl RingAnnouncer {
    /// The ring size the terminal reader uses.
    pub const DEFAULT_CAPACITY: usize = 256;

    /// A ring keeping at most `capacity` announcements (at least one).
    pub fn new(capacity: usize) -> Self {
        let capacity = capacity.max(1);
        RingAnnouncer {
            entries: std::collections::VecDeque::with_capacity(capacity),
            capacity,
        }
    }

    /// The announcements kept, oldest first.
    pub fn texts(&self) -> Vec<&str> {
        self.entries.iter().map(|(t, _)| t.as_str()).collect()
    }

    /// The most recent announcement.
    pub fn last(&self) -> Option<&str> {
        self.entries.back().map(|(t, _)| t.as_str())
    }

    /// How many announcements are kept.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// True when nothing was announced yet.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// The most kept.
    pub fn capacity(&self) -> usize {
        self.capacity
    }
}

impl Default for RingAnnouncer {
    fn default() -> Self {
        RingAnnouncer::new(Self::DEFAULT_CAPACITY)
    }
}

impl Announcer for RingAnnouncer {
    fn announce(&mut self, text: &str, priority: Priority) {
        if self.entries.len() == self.capacity {
            self.entries.pop_front();
        }
        self.entries.push_back((text.to_owned(), priority));
    }
}

/// Speaks announcements through a callback (the app passes one that calls
/// `SpeechService::say(text, SayMode::Announce)`).
pub struct SpeechAnnouncer<F: FnMut(&str, Priority)> {
    speak: F,
}

impl<F: FnMut(&str, Priority)> SpeechAnnouncer<F> {
    /// An announcer that calls `speak`.
    pub fn new(speak: F) -> Self {
        SpeechAnnouncer { speak }
    }
}

impl<F: FnMut(&str, Priority)> Announcer for SpeechAnnouncer<F> {
    fn announce(&mut self, text: &str, priority: Priority) {
        (self.speak)(text, priority);
    }
}

/// Keeps the latest announcement for display on a status line.
///
/// Terminal screen readers speak the status line when its text changes, so
/// the same message twice in a row ("No next heading") would be silent the
/// second time. [`seq`](Self::seq) changes on every announcement; a
/// frontend redraws (for example clears the line for one frame) when it
/// sees a new `seq` with unchanged text.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StatusLineAnnouncer {
    /// The text currently shown.
    pub current: Option<String>,
    /// Counts announcements; changes even when the text repeats.
    pub seq: u64,
    /// Priority of the current text.
    pub priority: Priority,
}

impl StatusLineAnnouncer {
    /// Clears the status line (a timeout expired).
    pub fn clear(&mut self) {
        self.current = None;
    }
}

impl Announcer for StatusLineAnnouncer {
    fn announce(&mut self, text: &str, priority: Priority) {
        self.current = Some(text.to_owned());
        self.priority = priority;
        self.seq = self.seq.wrapping_add(1);
    }
}

/// Sends every announcement to several announcers.
#[derive(Default)]
pub struct MultiAnnouncer {
    targets: Vec<Box<dyn Announcer>>,
}

impl MultiAnnouncer {
    /// An announcer with no targets.
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds a target.
    pub fn push(&mut self, a: Box<dyn Announcer>) {
        self.targets.push(a);
    }

    /// Number of targets.
    pub fn len(&self) -> usize {
        self.targets.len()
    }

    /// True when there are no targets.
    pub fn is_empty(&self) -> bool {
        self.targets.is_empty()
    }
}

impl Announcer for MultiAnnouncer {
    fn announce(&mut self, text: &str, priority: Priority) {
        for t in &mut self.targets {
            t.announce(text, priority);
        }
    }
}

/// A clonable, shared announcer. Give one clone to the app (boxed, as its
/// announcer) and keep another to read the state: the TUI draws the status
/// line from a `Shared<StatusLineAnnouncer>`, tests read a
/// `Shared<LogAnnouncer>`.
#[derive(Debug, Default)]
pub struct Shared<A>(Arc<Mutex<A>>);

impl<A> Clone for Shared<A> {
    fn clone(&self) -> Self {
        Shared(Arc::clone(&self.0))
    }
}

impl<A> Shared<A> {
    /// Wraps an announcer.
    pub fn new(inner: A) -> Self {
        Shared(Arc::new(Mutex::new(inner)))
    }

    /// Locks the announcer for reading or changing it.
    pub fn lock(&self) -> MutexGuard<'_, A> {
        // Announcers hold plain data; a panic elsewhere leaves it usable.
        self.0.lock().unwrap_or_else(|e| e.into_inner())
    }

    /// Runs `f` with the announcer.
    pub fn with<R>(&self, f: impl FnOnce(&mut A) -> R) -> R {
        f(&mut self.lock())
    }
}

impl<A: Clone> Shared<A> {
    /// A copy of the announcer's current state.
    pub fn snapshot(&self) -> A {
        self.lock().clone()
    }
}

impl<A: Announcer> Announcer for Shared<A> {
    fn announce(&mut self, text: &str, priority: Priority) {
        self.lock().announce(text, priority);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verbosity_filters() {
        let mut a = LogAnnouncer::default();
        a.announce_at(
            "detail",
            Priority::Polite,
            Verbosity::High,
            Verbosity::Normal,
        );
        a.announce_at("state", Priority::Polite, Verbosity::Low, Verbosity::Normal);
        assert_eq!(a.log, vec![("state".to_owned(), Priority::Polite)]);
    }

    #[test]
    fn the_ring_keeps_only_the_latest() {
        let mut r = RingAnnouncer::default();
        assert!(r.is_empty());
        assert_eq!(r.capacity(), 256);
        for i in 0..1000 {
            r.announce(&format!("message {i}"), Priority::Polite);
        }
        assert_eq!(r.len(), 256);
        assert_eq!(r.texts()[0], "message 744");
        assert_eq!(r.last(), Some("message 999"));
        let mut tiny = RingAnnouncer::new(0);
        tiny.announce("a", Priority::Polite);
        tiny.announce("b", Priority::Assertive);
        assert_eq!(tiny.texts(), vec!["b"]);
    }

    #[test]
    fn speech_announcer_calls_back() {
        let mut said = Vec::new();
        {
            let mut a = SpeechAnnouncer::new(|t: &str, _| said.push(t.to_owned()));
            a.announce("Rate 290", Priority::Assertive);
        }
        assert_eq!(said, vec!["Rate 290"]);
    }

    #[test]
    fn events_use_catalog_wording_and_priority() {
        let mut a = LogAnnouncer::default();
        a.announce_event(&Announcement::Rate { wpm: 300 }, Verbosity::Normal);
        a.announce_event(&Announcement::Paused, Verbosity::Low);
        a.announce_event(
            &Announcement::Opened {
                title: "Notes".into(),
            },
            Verbosity::Low,
        );
        assert_eq!(
            a.log,
            vec![
                ("Rate 300 words per minute".to_owned(), Priority::Assertive),
                ("Notes".to_owned(), Priority::Polite),
            ]
        );
        assert_eq!(a.texts(), vec!["Rate 300 words per minute", "Notes"]);
        assert_eq!(a.last(), Some("Notes"));
    }

    #[test]
    fn status_line_changes_seq_on_repeats() {
        let mut s = StatusLineAnnouncer::default();
        s.announce("No next heading", Priority::Assertive);
        let first = s.seq;
        s.announce("No next heading", Priority::Assertive);
        assert_ne!(s.seq, first);
        assert_eq!(s.current.as_deref(), Some("No next heading"));
        s.clear();
        assert_eq!(s.current, None);
    }

    #[test]
    fn shared_handles_see_the_same_state() {
        let log = Shared::new(LogAnnouncer::default());
        let status = Shared::new(StatusLineAnnouncer::default());
        let mut multi = MultiAnnouncer::new();
        multi.push(Box::new(log.clone()));
        multi.push(Box::new(status.clone()));
        assert_eq!(multi.len(), 2);
        let mut boxed: Box<dyn Announcer> = Box::new(multi);
        boxed.announce_event(&Announcement::SpeechCursor { on: true }, Verbosity::Normal);
        assert_eq!(log.snapshot().texts(), vec!["Speech cursor on"]);
        assert_eq!(
            status.with(|s| s.current.clone()).as_deref(),
            Some("Speech cursor on")
        );
    }

    /// The table in the crate docs is the generated one.
    #[test]
    fn crate_docs_hold_the_current_verbosity_table() {
        let src = include_str!("lib.rs").replace("\r\n", "\n");
        let start = src.find("//! <!-- VERBOSITY-TABLE-START -->\n").unwrap();
        let end = src.find("//! <!-- VERBOSITY-TABLE-END -->").unwrap();
        let body: String = src[start..end]
            .lines()
            .skip(1)
            .map(|l| format!("{}\n", l.trim_start_matches("//!").trim_start()))
            .collect();
        let expected = verbosity_table();
        assert!(
            body == expected,
            "update the table in crates/textweaver-a11y/src/lib.rs:\n{}",
            expected
                .lines()
                .map(|l| format!("//! {l}\n"))
                .collect::<String>()
        );
    }
}
