//! Symbol tables: LaTeX commands to Unicode, Unicode characters to their
//! class, and Unicode symbols and function names to spoken English.
//!
//! Both parsers produce Unicode text in the tree (`\alpha` and ASCIIMath
//! `alpha` both become `α`), so speech and MathML have one table each.

use crate::OpClass;

/// What a LaTeX command or a raw character stands for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Sym {
    /// An identifier or constant (`α`, `∞`).
    Ident(&'static str),
    /// An operator of the given class.
    Op(&'static str, OpClass),
}

use OpClass::{
    Binary as B, Close as C, Fence as F, Large as L, Open as O, Other as Q, Postfix as X,
    Prefix as P, Punctuation as U, Relation as R,
};

/// Greek letters and letter-like symbols by LaTeX command name.
fn latex_ident(name: &str) -> Option<&'static str> {
    Some(match name {
        "alpha" => "α",
        "beta" => "β",
        "gamma" => "γ",
        "delta" => "δ",
        "epsilon" => "ϵ",
        "varepsilon" => "ε",
        "zeta" => "ζ",
        "eta" => "η",
        "theta" => "θ",
        "vartheta" => "ϑ",
        "iota" => "ι",
        "kappa" => "κ",
        "varkappa" => "ϰ",
        "lambda" => "λ",
        "mu" => "μ",
        "nu" => "ν",
        "xi" => "ξ",
        "omicron" => "ο",
        "pi" => "π",
        "varpi" => "ϖ",
        "rho" => "ρ",
        "varrho" => "ϱ",
        "sigma" => "σ",
        "varsigma" => "ς",
        "tau" => "τ",
        "upsilon" => "υ",
        "phi" => "ϕ",
        "varphi" => "φ",
        "chi" => "χ",
        "psi" => "ψ",
        "omega" => "ω",
        "digamma" => "ϝ",
        "Gamma" | "varGamma" => "Γ",
        "Delta" | "varDelta" => "Δ",
        "Theta" | "varTheta" => "Θ",
        "Lambda" | "varLambda" => "Λ",
        "Xi" | "varXi" => "Ξ",
        "Pi" | "varPi" => "Π",
        "Sigma" | "varSigma" => "Σ",
        "Upsilon" | "varUpsilon" => "Υ",
        "Phi" | "varPhi" => "Φ",
        "Psi" | "varPsi" => "Ψ",
        "Omega" | "varOmega" => "Ω",
        "infty" => "∞",
        "emptyset" | "varnothing" => "∅",
        "aleph" => "ℵ",
        "beth" => "ℶ",
        "gimel" => "ℷ",
        "hbar" | "hslash" => "ℏ",
        "ell" => "ℓ",
        "wp" => "℘",
        "Re" => "ℜ",
        "Im" => "ℑ",
        "partial" => "∂",
        "nabla" => "∇",
        "imath" => "ı",
        "jmath" => "ȷ",
        "top" => "⊤",
        "bot" => "⊥",
        "angle" => "∠",
        "measuredangle" => "∡",
        "triangle" => "△",
        "Box" | "square" => "□",
        "blacksquare" => "■",
        "Diamond" => "◇",
        "backprime" => "‵",
        "complement" => "∁",
        "mho" => "℧",
        "eth" => "ð",
        "sharp" => "♯",
        "flat" => "♭",
        "natural" => "♮",
        "checkmark" => "✓",
        "clubsuit" => "♣",
        "diamondsuit" => "♢",
        "heartsuit" => "♡",
        "spadesuit" => "♠",
        "S" => "§",
        "P" => "¶",
        "pounds" => "£",
        "degree" => "°",
        "Bbbk" => "𝕜",
        _ => return None,
    })
}

/// Operators, relations, arrows, brackets, and punctuation by LaTeX command.
fn latex_op(name: &str) -> Option<(&'static str, OpClass)> {
    Some(match name {
        // binary operators
        "pm" => ("±", B),
        "mp" => ("∓", B),
        "times" => ("×", B),
        "div" => ("÷", B),
        "cdot" | "cdotp" | "centerdot" => ("⋅", B),
        "ast" => ("∗", B),
        "star" => ("⋆", B),
        "circ" => ("∘", B),
        "bullet" => ("∙", B),
        "oplus" => ("⊕", B),
        "ominus" => ("⊖", B),
        "otimes" => ("⊗", B),
        "oslash" => ("⊘", B),
        "odot" => ("⊙", B),
        "cup" => ("∪", B),
        "cap" => ("∩", B),
        "sqcup" => ("⊔", B),
        "sqcap" => ("⊓", B),
        "uplus" => ("⊎", B),
        "wedge" | "land" => ("∧", B),
        "vee" | "lor" => ("∨", B),
        "setminus" | "smallsetminus" => ("∖", B),
        "backslash" => ("\\", Q),
        "wr" => ("≀", B),
        "diamond" => ("⋄", B),
        "bigtriangleup" => ("△", B),
        "bigtriangledown" => ("▽", B),
        "triangleleft" => ("◃", B),
        "triangleright" => ("▹", B),
        "lhd" => ("⊲", B),
        "rhd" => ("⊳", B),
        "unlhd" => ("⊴", B),
        "unrhd" => ("⊵", B),
        "amalg" => ("⨿", B),
        "dagger" => ("†", B),
        "ddagger" => ("‡", B),
        "ltimes" => ("⋉", B),
        "rtimes" => ("⋊", B),
        "dotplus" => ("∔", B),
        "boxplus" => ("⊞", B),
        "boxminus" => ("⊟", B),
        "boxtimes" => ("⊠", B),
        "boxdot" => ("⊡", B),
        "intercal" => ("⊺", B),
        "veebar" => ("⊻", B),
        "barwedge" => ("⌅", B),
        "divideontimes" => ("⋇", B),
        // relations
        "leq" | "le" => ("≤", R),
        "geq" | "ge" => ("≥", R),
        "leqslant" => ("⩽", R),
        "geqslant" => ("⩾", R),
        "neq" | "ne" => ("≠", R),
        "equiv" => ("≡", R),
        "approx" => ("≈", R),
        "approxeq" => ("≊", R),
        "cong" => ("≅", R),
        "sim" => ("∼", R),
        "simeq" => ("≃", R),
        "propto" | "varpropto" => ("∝", R),
        "ll" => ("≪", R),
        "gg" => ("≫", R),
        "lll" => ("⋘", R),
        "ggg" => ("⋙", R),
        "prec" => ("≺", R),
        "succ" => ("≻", R),
        "preceq" => ("⪯", R),
        "succeq" => ("⪰", R),
        "subset" => ("⊂", R),
        "supset" => ("⊃", R),
        "subseteq" => ("⊆", R),
        "supseteq" => ("⊇", R),
        "subsetneq" => ("⊊", R),
        "supsetneq" => ("⊋", R),
        "nsubseteq" => ("⊈", R),
        "nsupseteq" => ("⊉", R),
        "sqsubset" => ("⊏", R),
        "sqsupset" => ("⊐", R),
        "sqsubseteq" => ("⊑", R),
        "sqsupseteq" => ("⊒", R),
        "in" | "isin" => ("∈", R),
        "notin" => ("∉", R),
        "ni" | "owns" => ("∋", R),
        "mid" => ("∣", R),
        "nmid" => ("∤", R),
        "parallel" => ("∥", R),
        "nparallel" => ("∦", R),
        "perp" => ("⟂", R),
        "vdash" => ("⊢", R),
        "dashv" => ("⊣", R),
        "models" | "vDash" => ("⊨", R),
        "doteq" => ("≐", R),
        "asymp" => ("≍", R),
        "bowtie" | "Join" => ("⋈", R),
        "smile" => ("⌣", R),
        "frown" => ("⌢", R),
        "lesssim" => ("≲", R),
        "gtrsim" => ("≳", R),
        "lessgtr" => ("≶", R),
        "nless" => ("≮", R),
        "ngtr" => ("≯", R),
        "nleq" => ("≰", R),
        "ngeq" => ("≱", R),
        "nsim" => ("≁", R),
        "ncong" => ("≇", R),
        "triangleq" => ("≜", R),
        "coloneqq" | "coloneq" => ("≔", R),
        "therefore" => ("∴", R),
        "because" => ("∵", R),
        // arrows
        "to" | "rightarrow" => ("→", R),
        "leftarrow" | "gets" => ("←", R),
        "leftrightarrow" => ("↔", R),
        "Rightarrow" => ("⇒", R),
        "Leftarrow" => ("⇐", R),
        "Leftrightarrow" => ("⇔", R),
        "implies" | "Longrightarrow" => ("⟹", R),
        "impliedby" | "Longleftarrow" => ("⟸", R),
        "iff" | "Longleftrightarrow" => ("⟺", R),
        "longrightarrow" => ("⟶", R),
        "longleftarrow" => ("⟵", R),
        "longleftrightarrow" => ("⟷", R),
        "mapsto" => ("↦", R),
        "longmapsto" => ("⟼", R),
        "uparrow" => ("↑", R),
        "downarrow" => ("↓", R),
        "updownarrow" => ("↕", R),
        "Uparrow" => ("⇑", R),
        "Downarrow" => ("⇓", R),
        "Updownarrow" => ("⇕", R),
        "nearrow" => ("↗", R),
        "searrow" => ("↘", R),
        "swarrow" => ("↙", R),
        "nwarrow" => ("↖", R),
        "hookrightarrow" => ("↪", R),
        "hookleftarrow" => ("↩", R),
        "rightharpoonup" => ("⇀", R),
        "rightharpoondown" => ("⇁", R),
        "leftharpoonup" => ("↼", R),
        "leftharpoondown" => ("↽", R),
        "rightleftharpoons" => ("⇌", R),
        "leftrightharpoons" => ("⇋", R),
        "twoheadrightarrow" => ("↠", R),
        "rightarrowtail" => ("↣", R),
        "leadsto" | "rightsquigarrow" => ("⇝", R),
        "nrightarrow" => ("↛", R),
        "nleftarrow" => ("↚", R),
        // large operators
        "sum" => ("∑", L),
        "prod" => ("∏", L),
        "coprod" => ("∐", L),
        "int" => ("∫", L),
        "iint" => ("∬", L),
        "iiint" => ("∭", L),
        "iiiint" => ("⨌", L),
        "oint" => ("∮", L),
        "oiint" => ("∯", L),
        "bigcup" => ("⋃", L),
        "bigcap" => ("⋂", L),
        "bigoplus" => ("⨁", L),
        "bigotimes" => ("⨂", L),
        "bigodot" => ("⨀", L),
        "biguplus" => ("⨄", L),
        "bigsqcup" => ("⨆", L),
        "bigvee" => ("⋁", L),
        "bigwedge" => ("⋀", L),
        // brackets
        "langle" => ("⟨", O),
        "rangle" => ("⟩", C),
        "lbrace" | "{" => ("{", O),
        "rbrace" | "}" => ("}", C),
        "lbrack" => ("[", O),
        "rbrack" => ("]", C),
        "lfloor" => ("⌊", O),
        "rfloor" => ("⌋", C),
        "lceil" => ("⌈", O),
        "rceil" => ("⌉", C),
        "lvert" => ("|", O),
        "rvert" => ("|", C),
        "lVert" => ("‖", O),
        "rVert" => ("‖", C),
        "lgroup" => ("⟮", O),
        "rgroup" => ("⟯", C),
        "llbracket" => ("⟦", O),
        "rrbracket" => ("⟧", C),
        "vert" => ("|", F),
        "Vert" | "|" => ("‖", F),
        // punctuation and dots
        "ldots" | "dots" | "dotsc" | "dotso" => ("…", U),
        "cdots" | "dotsb" | "dotsm" | "dotsi" => ("⋯", U),
        "vdots" => ("⋮", U),
        "ddots" => ("⋱", U),
        "colon" => (":", U),
        // prefix and postfix
        "forall" => ("∀", P),
        "exists" => ("∃", P),
        "nexists" => ("∄", P),
        "neg" | "lnot" => ("¬", P),
        "prime" => ("′", X),
        // escaped characters
        "%" => ("%", Q),
        "$" => ("$", Q),
        "#" => ("#", Q),
        "&" => ("&", Q),
        "_" => ("_", Q),
        _ => return None,
    })
}

/// A LaTeX command that stands for a single symbol.
pub(crate) fn latex_symbol(name: &str) -> Option<Sym> {
    if let Some(s) = latex_ident(name) {
        return Some(Sym::Ident(s));
    }
    latex_op(name).map(|(s, c)| Sym::Op(s, c))
}

/// LaTeX's named functions (`\sin`, `\lim`).
pub(crate) fn latex_function(name: &str) -> Option<&'static str> {
    const NAMES: &[&str] = &[
        "sin", "cos", "tan", "cot", "sec", "csc", "sinh", "cosh", "tanh", "coth", "sech", "csch",
        "arcsin", "arccos", "arctan", "arcsec", "arccsc", "arccot", "arg", "deg", "det", "dim",
        "exp", "gcd", "lcm", "hom", "inf", "ker", "lg", "lim", "liminf", "limsup", "ln", "log",
        "max", "min", "Pr", "sup", "mod", "bmod", "argmax", "argmin", "tr", "Tr", "rank", "sgn",
    ];
    NAMES.iter().copied().find(|n| *n == name)
}

/// Functions whose scripts are limits set below and above (`\lim_{x\to0}`).
pub(crate) fn takes_limits(function: &str) -> bool {
    matches!(
        function,
        "lim"
            | "liminf"
            | "limsup"
            | "max"
            | "min"
            | "sup"
            | "inf"
            | "det"
            | "gcd"
            | "Pr"
            | "argmax"
            | "argmin"
            | "Lim"
    )
}

/// The class of a raw character typed in math.
pub(crate) fn char_symbol(c: char) -> Option<Sym> {
    let op = |s: &'static str, cl: OpClass| Some(Sym::Op(s, cl));
    match c {
        '+' => op("+", B),
        '-' | '−' => op("−", B),
        '*' => op("∗", B),
        '/' => op("/", B),
        '=' => op("=", R),
        '<' => op("<", R),
        '>' => op(">", R),
        '(' => op("(", O),
        ')' => op(")", C),
        '[' => op("[", O),
        ']' => op("]", C),
        '|' => op("|", F),
        ',' => op(",", U),
        ';' => op(";", U),
        ':' => op(":", U),
        '.' => op(".", U),
        '?' => op("?", U),
        '!' => op("!", X),
        '\'' => op("′", X),
        '@' => op("@", Q),
        '"' => op("\"", Q),
        '`' => op("`", Q),
        _ => {
            let mut buf = [0u8; 4];
            let s: &str = c.encode_utf8(&mut buf);
            if let Some(sym) = unicode_symbol(s) {
                return Some(sym);
            }
            None
        }
    }
}

/// Classifies a Unicode symbol typed directly (`≤`, `α`, `∑`) by looking it
/// up in the LaTeX tables.
fn unicode_symbol(s: &str) -> Option<Sym> {
    UNICODE_INDEX
        .iter()
        .find(|(t, _)| *t == s)
        .map(|(_, sym)| *sym)
}

/// Unicode text of every LaTeX symbol, for classifying typed symbols.
static UNICODE_INDEX: std::sync::LazyLock<Vec<(&'static str, Sym)>> =
    std::sync::LazyLock::new(|| {
        let mut out = Vec::new();
        for name in LATEX_NAMES {
            if let Some(sym) = latex_symbol(name) {
                let text = match sym {
                    Sym::Ident(t) | Sym::Op(t, _) => t,
                };
                if !out.iter().any(|(t, _)| *t == text) {
                    out.push((text, sym));
                }
            }
        }
        for (t, sym) in [
            ("×", Sym::Op("×", B)),
            ("÷", Sym::Op("÷", B)),
            ("·", Sym::Op("⋅", B)),
            ("∓", Sym::Op("∓", B)),
            ("√", Sym::Op("√", P)),
            ("°", Sym::Op("°", X)),
            ("″", Sym::Op("″", X)),
            ("‴", Sym::Op("‴", X)),
            ("ℝ", Sym::Ident("ℝ")),
            ("ℕ", Sym::Ident("ℕ")),
            ("ℤ", Sym::Ident("ℤ")),
            ("ℚ", Sym::Ident("ℚ")),
            ("ℂ", Sym::Ident("ℂ")),
        ] {
            if !out.iter().any(|(x, _)| *x == t) {
                out.push((t, sym));
            }
        }
        out
    });

/// Every command name the tables know, used to build [`UNICODE_INDEX`] and
/// by tests.
pub(crate) const LATEX_NAMES: &[&str] = &[
    "alpha",
    "beta",
    "gamma",
    "delta",
    "epsilon",
    "varepsilon",
    "zeta",
    "eta",
    "theta",
    "vartheta",
    "iota",
    "kappa",
    "varkappa",
    "lambda",
    "mu",
    "nu",
    "xi",
    "omicron",
    "pi",
    "varpi",
    "rho",
    "varrho",
    "sigma",
    "varsigma",
    "tau",
    "upsilon",
    "phi",
    "varphi",
    "chi",
    "psi",
    "omega",
    "digamma",
    "Gamma",
    "Delta",
    "Theta",
    "Lambda",
    "Xi",
    "Pi",
    "Sigma",
    "Upsilon",
    "Phi",
    "Psi",
    "Omega",
    "infty",
    "emptyset",
    "aleph",
    "beth",
    "gimel",
    "hbar",
    "ell",
    "wp",
    "Re",
    "Im",
    "partial",
    "nabla",
    "imath",
    "jmath",
    "top",
    "bot",
    "angle",
    "measuredangle",
    "triangle",
    "square",
    "blacksquare",
    "Diamond",
    "backprime",
    "complement",
    "mho",
    "eth",
    "sharp",
    "flat",
    "natural",
    "checkmark",
    "clubsuit",
    "diamondsuit",
    "heartsuit",
    "spadesuit",
    "S",
    "P",
    "pounds",
    "degree",
    "pm",
    "mp",
    "times",
    "div",
    "cdot",
    "ast",
    "star",
    "circ",
    "bullet",
    "oplus",
    "ominus",
    "otimes",
    "oslash",
    "odot",
    "cup",
    "cap",
    "sqcup",
    "sqcap",
    "uplus",
    "wedge",
    "vee",
    "setminus",
    "wr",
    "diamond",
    "bigtriangleup",
    "bigtriangledown",
    "triangleleft",
    "triangleright",
    "lhd",
    "rhd",
    "unlhd",
    "unrhd",
    "amalg",
    "dagger",
    "ddagger",
    "ltimes",
    "rtimes",
    "dotplus",
    "boxplus",
    "boxminus",
    "boxtimes",
    "boxdot",
    "intercal",
    "veebar",
    "barwedge",
    "divideontimes",
    "leq",
    "geq",
    "leqslant",
    "geqslant",
    "neq",
    "equiv",
    "approx",
    "approxeq",
    "cong",
    "sim",
    "simeq",
    "propto",
    "ll",
    "gg",
    "lll",
    "ggg",
    "prec",
    "succ",
    "preceq",
    "succeq",
    "subset",
    "supset",
    "subseteq",
    "supseteq",
    "subsetneq",
    "supsetneq",
    "nsubseteq",
    "nsupseteq",
    "sqsubset",
    "sqsupset",
    "sqsubseteq",
    "sqsupseteq",
    "in",
    "notin",
    "ni",
    "mid",
    "nmid",
    "parallel",
    "nparallel",
    "perp",
    "vdash",
    "dashv",
    "models",
    "doteq",
    "asymp",
    "bowtie",
    "smile",
    "frown",
    "lesssim",
    "gtrsim",
    "lessgtr",
    "nless",
    "ngtr",
    "nleq",
    "ngeq",
    "nsim",
    "ncong",
    "triangleq",
    "coloneqq",
    "therefore",
    "because",
    "rightarrow",
    "leftarrow",
    "leftrightarrow",
    "Rightarrow",
    "Leftarrow",
    "Leftrightarrow",
    "implies",
    "impliedby",
    "iff",
    "longrightarrow",
    "longleftarrow",
    "longleftrightarrow",
    "mapsto",
    "longmapsto",
    "uparrow",
    "downarrow",
    "updownarrow",
    "Uparrow",
    "Downarrow",
    "Updownarrow",
    "nearrow",
    "searrow",
    "swarrow",
    "nwarrow",
    "hookrightarrow",
    "hookleftarrow",
    "rightharpoonup",
    "rightharpoondown",
    "leftharpoonup",
    "leftharpoondown",
    "rightleftharpoons",
    "leftrightharpoons",
    "twoheadrightarrow",
    "rightarrowtail",
    "leadsto",
    "nrightarrow",
    "nleftarrow",
    "sum",
    "prod",
    "coprod",
    "int",
    "iint",
    "iiint",
    "iiiint",
    "oint",
    "oiint",
    "bigcup",
    "bigcap",
    "bigoplus",
    "bigotimes",
    "bigodot",
    "biguplus",
    "bigsqcup",
    "bigvee",
    "bigwedge",
    "langle",
    "rangle",
    "lfloor",
    "rfloor",
    "lceil",
    "rceil",
    "lgroup",
    "rgroup",
    "llbracket",
    "rrbracket",
    "vert",
    "Vert",
    "ldots",
    "cdots",
    "vdots",
    "ddots",
    "forall",
    "exists",
    "nexists",
    "neg",
    "prime",
];

/// The negated form of a relation (`\not=` is `≠`).
pub(crate) fn negate(text: &str) -> String {
    let s = match text {
        "=" => "≠",
        "∈" => "∉",
        "∋" => "∌",
        "⊂" => "⊄",
        "⊃" => "⊅",
        "⊆" => "⊈",
        "⊇" => "⊉",
        "≡" => "≢",
        "<" => "≮",
        ">" => "≯",
        "≤" => "≰",
        "≥" => "≱",
        "∼" => "≁",
        "≈" => "≉",
        "≅" => "≇",
        "∃" => "∄",
        "∣" => "∤",
        "∥" => "∦",
        "≺" => "⊀",
        "≻" => "⊁",
        "→" => "↛",
        "←" => "↚",
        "⊢" => "⊬",
        "⊨" => "⊭",
        _ => return format!("{text}\u{0338}"),
    };
    s.to_owned()
}

/// Spoken English for a symbol's Unicode text, at normal verbosity.
pub(crate) fn words(text: &str) -> Option<&'static str> {
    Some(match text {
        // Greek
        "α" => "alpha",
        "β" => "beta",
        "γ" => "gamma",
        "δ" => "delta",
        "ϵ" | "ε" => "epsilon",
        "ζ" => "zeta",
        "η" => "eta",
        "θ" | "ϑ" => "theta",
        "ι" => "iota",
        "κ" | "ϰ" => "kappa",
        "λ" => "lambda",
        "μ" => "mu",
        "ν" => "nu",
        "ξ" => "xi",
        "ο" => "omicron",
        "π" | "ϖ" => "pi",
        "ρ" | "ϱ" => "rho",
        "σ" | "ς" => "sigma",
        "τ" => "tau",
        "υ" => "upsilon",
        "ϕ" | "φ" => "phi",
        "χ" => "chi",
        "ψ" => "psi",
        "ω" => "omega",
        "ϝ" => "digamma",
        "Γ" => "capital gamma",
        "Δ" => "capital delta",
        "Θ" => "capital theta",
        "Λ" => "capital lambda",
        "Ξ" => "capital xi",
        "Π" => "capital pi",
        "Σ" => "capital sigma",
        "Υ" => "capital upsilon",
        "Φ" => "capital phi",
        "Ψ" => "capital psi",
        "Ω" => "capital omega",
        // letter-like
        "∞" => "infinity",
        "∅" => "the empty set",
        "ℵ" => "aleph",
        "ℶ" => "beth",
        "ℷ" => "gimel",
        "ℏ" => "h bar",
        "ℓ" => "script l",
        "℘" => "Weierstrass p",
        "ℜ" => "real part",
        "ℑ" => "imaginary part",
        "∂" => "partial",
        "∇" => "del",
        "ı" => "dotless i",
        "ȷ" => "dotless j",
        "⊤" => "top",
        "⊥" => "perpendicular",
        "∠" => "angle",
        "∡" => "measured angle",
        "△" => "triangle",
        "▽" => "down triangle",
        "□" => "square",
        "■" => "black square",
        "◇" => "diamond",
        "‵" => "back prime",
        "∁" => "complement",
        "℧" => "mho",
        "ð" => "eth",
        "♯" => "sharp",
        "♭" => "flat",
        "♮" => "natural",
        "✓" => "check mark",
        "♣" => "clubs",
        "♢" => "diamonds",
        "♡" => "hearts",
        "♠" => "spades",
        "§" => "section",
        "¶" => "paragraph",
        "£" => "pounds",
        "°" => "degrees",
        "ℝ" => "the real numbers",
        "ℕ" => "the natural numbers",
        "ℤ" => "the integers",
        "ℚ" => "the rational numbers",
        "ℂ" => "the complex numbers",
        "𝕜" => "the field k",
        // binary operators
        "+" => "plus",
        "−" | "-" => "minus",
        "±" => "plus or minus",
        "∓" => "minus or plus",
        "×" | "⋅" | "·" => "times",
        "÷" | "/" => "divided by",
        "∗" | "*" => "times",
        "⋆" => "star",
        "∘" => "composed with",
        "∙" => "bullet",
        "⊕" => "circled plus",
        "⊖" => "circled minus",
        "⊗" => "circled times",
        "⊘" => "circled slash",
        "⊙" => "circled dot",
        "∪" => "union",
        "∩" => "intersection",
        "⊔" => "square union",
        "⊓" => "square intersection",
        "⊎" => "multiset union",
        "∧" => "and",
        "∨" => "or",
        "∖" | "\\" => "set minus",
        "≀" => "wreath product",
        "⋄" => "diamond",
        "◃" => "left triangle",
        "▹" => "right triangle",
        "⊲" => "normal subgroup of",
        "⊳" => "contains as normal subgroup",
        "⊴" => "normal subgroup of or equal to",
        "⊵" => "contains as normal subgroup or equal to",
        "⨿" => "amalgamation",
        "†" => "dagger",
        "‡" => "double dagger",
        "⋉" => "left semidirect product",
        "⋊" => "right semidirect product",
        "∔" => "dot plus",
        "⊞" => "squared plus",
        "⊟" => "squared minus",
        "⊠" => "squared times",
        "⊡" => "squared dot",
        "⊺" => "intercalate",
        "⊻" => "exclusive or",
        "⌅" => "nand",
        "⋇" => "division times",
        // relations
        "=" => "equals",
        "≠" => "not equal to",
        "<" => "less than",
        ">" => "greater than",
        "≤" | "⩽" => "less than or equal to",
        "≥" | "⩾" => "greater than or equal to",
        "≮" => "not less than",
        "≯" => "not greater than",
        "≰" => "neither less than nor equal to",
        "≱" => "neither greater than nor equal to",
        "≡" => "is equivalent to",
        "≢" => "is not equivalent to",
        "≈" => "approximately equal to",
        "≉" => "not approximately equal to",
        "≊" => "almost equal or equal to",
        "≅" => "is congruent to",
        "≇" => "is not congruent to",
        "∼" => "is similar to",
        "≁" => "is not similar to",
        "≃" => "is asymptotically equal to",
        "∝" => "is proportional to",
        "≪" => "much less than",
        "≫" => "much greater than",
        "⋘" => "very much less than",
        "⋙" => "very much greater than",
        "≺" => "precedes",
        "≻" => "succeeds",
        "⊀" => "does not precede",
        "⊁" => "does not succeed",
        "⪯" => "precedes or equals",
        "⪰" => "succeeds or equals",
        "⊂" => "is a subset of",
        "⊃" => "is a superset of",
        "⊆" => "is a subset of or equal to",
        "⊇" => "is a superset of or equal to",
        "⊊" => "is a proper subset of",
        "⊋" => "is a proper superset of",
        "⊄" => "is not a subset of",
        "⊅" => "is not a superset of",
        "⊈" => "is neither a subset of nor equal to",
        "⊉" => "is neither a superset of nor equal to",
        "⊏" => "is a square subset of",
        "⊐" => "is a square superset of",
        "⊑" => "is a square subset of or equal to",
        "⊒" => "is a square superset of or equal to",
        "∈" => "is an element of",
        "∉" => "is not an element of",
        "∋" => "contains the element",
        "∌" => "does not contain the element",
        "∣" => "divides",
        "∤" => "does not divide",
        "∥" => "is parallel to",
        "∦" => "is not parallel to",
        "⟂" => "is perpendicular to",
        "⊢" => "proves",
        "⊬" => "does not prove",
        "⊣" => "is proved by",
        "⊨" => "models",
        "⊭" => "does not model",
        "≐" => "approaches the limit",
        "≍" => "is equivalent to",
        "⋈" => "bowtie",
        "⌣" => "smile",
        "⌢" => "frown",
        "≲" => "less than or similar to",
        "≳" => "greater than or similar to",
        "≶" => "less than or greater than",
        "≜" => "is defined as",
        "≔" | ":=" => "is defined as",
        "∴" => "therefore",
        "∵" => "because",
        // arrows
        "→" | "⟶" => "approaches",
        "←" | "⟵" => "left arrow",
        "↔" | "⟷" => "left right arrow",
        "⇒" | "⟹" => "implies",
        "⇐" | "⟸" => "is implied by",
        "⇔" | "⟺" => "if and only if",
        "↦" | "⟼" => "maps to",
        "↑" => "up arrow",
        "↓" => "down arrow",
        "↕" => "up down arrow",
        "⇑" => "double up arrow",
        "⇓" => "double down arrow",
        "⇕" => "double up down arrow",
        "↗" => "north east arrow",
        "↘" => "south east arrow",
        "↙" => "south west arrow",
        "↖" => "north west arrow",
        "↪" => "hook right arrow",
        "↩" => "hook left arrow",
        "⇀" | "⇁" => "right harpoon",
        "↼" | "↽" => "left harpoon",
        "⇌" => "is in equilibrium with",
        "⇋" => "left right harpoons",
        "↠" => "maps onto",
        "↣" => "maps one to one into",
        "⤖" => "maps one to one onto",
        "⇝" => "leads to",
        "↛" => "does not approach",
        "↚" => "not left arrow",
        // large operators
        "∑" => "sum",
        "∏" => "product",
        "∐" => "coproduct",
        "∫" => "integral",
        "∬" => "double integral",
        "∭" => "triple integral",
        "⨌" => "quadruple integral",
        "∮" => "contour integral",
        "∯" => "surface integral",
        "⋃" => "union",
        "⋂" => "intersection",
        "⨁" => "direct sum",
        "⨂" => "tensor product",
        "⨀" => "circled dot product",
        "⨄" => "multiset union",
        "⨆" => "square union",
        "⋁" => "disjunction",
        "⋀" => "conjunction",
        // brackets
        "(" => "open paren",
        ")" => "close paren",
        "[" => "open bracket",
        "]" => "close bracket",
        "{" => "open brace",
        "}" => "close brace",
        "⟨" => "open angle bracket",
        "⟩" => "close angle bracket",
        "⌊" => "left floor",
        "⌋" => "right floor",
        "⌈" => "left ceiling",
        "⌉" => "right ceiling",
        "|" => "vertical bar",
        "‖" => "double vertical bar",
        "⟮" => "open group",
        "⟯" => "close group",
        "⟦" => "open double bracket",
        "⟧" => "close double bracket",
        // punctuation
        "," => "comma",
        ";" => "semicolon",
        ":" => "colon",
        "?" => "question mark",
        "…" | "⋯" | "..." => "dot dot dot",
        "⋮" => "vertical dots",
        "⋱" => "diagonal dots",
        // prefix and postfix
        "∀" => "for all",
        "∃" => "there exists",
        "∄" => "there does not exist",
        "¬" => "not",
        "√" => "square root",
        "!" => "factorial",
        "′" => "prime",
        "″" => "double prime",
        "‴" => "triple prime",
        "%" => "percent",
        "$" => "dollars",
        "#" => "number",
        "&" => "and",
        "_" => "underscore",
        "@" => "at",
        _ => return None,
    })
}

/// True for trigonometric and hyperbolic functions, which are read without
/// "of" before a plain argument ("sine x"), as ClearSpeak does.
pub(crate) fn is_trig(name: &str) -> bool {
    let n = name.to_ascii_lowercase();
    matches!(
        n.as_str(),
        "sin"
            | "cos"
            | "tan"
            | "cot"
            | "sec"
            | "csc"
            | "sinh"
            | "cosh"
            | "tanh"
            | "coth"
            | "sech"
            | "csch"
            | "arcsin"
            | "arccos"
            | "arctan"
            | "arcsec"
            | "arccsc"
            | "arccot"
    )
}

/// Spoken English for a named function.
pub(crate) fn function_words(name: &str) -> String {
    let lower = name.to_ascii_lowercase();
    let w = match lower.as_str() {
        "sin" => "sine",
        "cos" => "cosine",
        "tan" => "tangent",
        "cot" => "cotangent",
        "sec" => "secant",
        "csc" => "cosecant",
        "sinh" => "hyperbolic sine",
        "cosh" => "hyperbolic cosine",
        "tanh" => "hyperbolic tangent",
        "coth" => "hyperbolic cotangent",
        "sech" => "hyperbolic secant",
        "csch" => "hyperbolic cosecant",
        "arcsin" => "arcsine",
        "arccos" => "arccosine",
        "arctan" => "arctangent",
        "arcsec" => "arcsecant",
        "arccsc" => "arccosecant",
        "arccot" => "arccotangent",
        "ln" => "natural log",
        "log" | "lg" => "log",
        "exp" => "exponential",
        "lim" => "limit",
        "liminf" => "limit inferior",
        "limsup" => "limit superior",
        "max" => "maximum",
        "min" => "minimum",
        "sup" => "supremum",
        "inf" => "infimum",
        "argmax" => "arg max",
        "argmin" => "arg min",
        "det" => "determinant",
        "dim" => "dimension",
        "ker" => "kernel",
        "deg" => "degree",
        "gcd" => "G C D",
        "lcm" => "L C M",
        "lub" => "least upper bound",
        "glb" => "greatest lower bound",
        "pr" => "probability",
        "mod" | "bmod" => "mod",
        "tr" => "trace",
        "sgn" => "sign",
        _ => return name.to_owned(),
    };
    w.to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{NodeKind, parse_latex};

    /// Every LaTeX symbol command parses to its Unicode token and has a
    /// spoken name.
    #[test]
    fn every_latex_symbol() {
        for name in LATEX_NAMES {
            let sym = latex_symbol(name).unwrap_or_else(|| panic!("\\{name} has no symbol"));
            let text = match sym {
                Sym::Ident(t) | Sym::Op(t, _) => t,
            };
            let m = parse_latex(&format!("\\{name}"));
            assert!(m.is_clean(), "\\{name}: {:?}", m.diagnostics);
            let NodeKind::Row(items) = &m.root.kind else {
                panic!("\\{name}");
            };
            assert_eq!(items.len(), 1, "\\{name}");
            assert_eq!(items[0].token_text(), Some(text), "\\{name}");
            assert!(
                words(text).is_some(),
                "\\{name} ({text}) has no spoken name"
            );
        }
    }

    #[test]
    fn every_function_has_words() {
        for name in [
            "sin", "cos", "tan", "cot", "sec", "csc", "sinh", "cosh", "tanh", "coth", "arcsin",
            "arccos", "arctan", "ln", "exp", "lim", "max", "min", "sup", "inf", "det",
        ] {
            assert!(latex_function(name).is_some(), "{name}");
            assert_ne!(function_words(name), name, "{name}");
        }
    }

    #[test]
    fn negation() {
        assert_eq!(negate("="), "≠");
        assert_eq!(negate("∈"), "∉");
        assert_eq!(negate("⊲"), "⊲\u{0338}");
    }
}
