//! Help generated from the keymap: the in-app keyboard help and
//! `docs/keyboard.md` (`cargo xtask keyboard`) come from the same data, so
//! they cannot disagree with the bindings.

use std::fmt::Write as _;

use crate::{ActionId, Binding, Category, Frontend, Keymap, Layer, Platform, Preset};

/// One action and its bindings.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HelpEntry {
    /// The action.
    pub action: ActionId,
    /// Its bindings, in definition order.
    pub bindings: Vec<Binding>,
}

impl HelpEntry {
    /// Keys as text, each with its layer unless global:
    /// `Alt+. or . (browse)`. "command palette" for a palette command
    /// without keys, "unbound" for any other action without keys.
    pub fn keys_text(&self) -> String {
        if self.bindings.is_empty() {
            return if self.action.is_palette_command() {
                "command palette".to_owned()
            } else {
                "unbound".to_owned()
            };
        }
        self.bindings
            .iter()
            .map(|b| match b.layer {
                Layer::Global => b.chord.to_string(),
                l => format!("{} ({})", b.chord, l.name()),
            })
            .collect::<Vec<_>>()
            .join(" or ")
    }

    /// The entry as one sentence for speech: "Move to the next sentence:
    /// Alt period, or period in browse mode."
    pub fn spoken(&self) -> String {
        if self.bindings.is_empty() {
            return if self.action.is_palette_command() {
                format!("{}: from the command palette.", self.action.help())
            } else {
                format!("{}: no key.", self.action.help())
            };
        }
        let keys: Vec<String> = self
            .bindings
            .iter()
            .map(|b| match b.layer {
                Layer::Global => b.chord.spoken(),
                l => format!("{} in {} mode", b.chord.spoken(), l.name()),
            })
            .collect();
        format!("{}: {}.", self.action.help(), keys.join(", or "))
    }
}

/// The actions of one category.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HelpSection {
    /// The category.
    pub category: Category,
    /// Its actions, in help order.
    pub entries: Vec<HelpEntry>,
}

impl Keymap {
    /// Help for this keymap (defaults plus the user's overrides), grouped
    /// by category in help order. Every action is listed, bound or not.
    pub fn help(&self) -> Vec<HelpSection> {
        Category::ALL
            .iter()
            .map(|&category| HelpSection {
                category,
                entries: ActionId::in_category(category)
                    .map(|action| HelpEntry {
                        action,
                        bindings: self.bindings_for(action),
                    })
                    .collect(),
            })
            .collect()
    }
}

fn cell(action: ActionId, bindings: &[Binding]) -> String {
    cell_with(action, bindings, |c| c.to_string())
}

/// A table cell for the GUI on macOS: Option for Alt.
fn mac_cell(action: ActionId, bindings: &[Binding]) -> String {
    cell_with(action, bindings, crate::KeyChord::mac_text)
}

fn cell_with(
    action: ActionId,
    bindings: &[Binding],
    text: impl Fn(&crate::KeyChord) -> String,
) -> String {
    if bindings.is_empty() {
        return if action.is_palette_command() {
            "palette".to_owned()
        } else {
            "none".to_owned()
        };
    }
    bindings
        .iter()
        .map(|b| {
            let chord = text(&b.chord);
            // Backticks inside a code span need a longer fence.
            let code = if chord.contains('`') {
                format!("`` {chord} ``")
            } else {
                format!("`{chord}`")
            };
            match b.layer {
                Layer::Global => code,
                l => format!("{code} ({})", l.name()),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
        .replace('|', "\\|")
}

const INTRO: &str = "\
# Keyboard reference

Generated by `cargo xtask keyboard` from `crates/textweaver-keymap`; do not edit by hand.
The in-app keyboard help shows the same table with your own overrides applied.

## What changed

On Tuesday, September 29, 2026 (Wave 6): **F10 opens the menus** in the terminal, as F10 does in Windows programs (File, Edit, View, Reading, Speech, Tools, and Help). Previous chapter keeps `Alt+PageUp` and `Shift+D`; next chapter keeps `F11`, `Alt+PageDown`, and `d`. **On macOS the GUI uses Mac keys**, not Ctrl renamed: Option with the arrows moves by word and paragraph, Command with the arrows goes to the ends of the line and the document, Command runs commands, and nothing takes VoiceOver's Ctrl+Option (see the GUI on macOS column). New keys: `Ctrl+F9` cycles the interface announcements (off, minimal, normal, full), `Ctrl+Shift+F9` starts and stops dictation, and `Shift+F1` says what the next key does.

On Saturday, September 26, 2026, the default keys became the quick navigation keys of NVDA's and JAWS's browse mode. To keep the earlier keys, set `preset = \"classic\"` under `[keyboard]` in `settings.toml` (see [the classic preset](#the-classic-preset)). Old key, then where its command went, in the terminal:

- `.` (next sentence): now `Alt+Down` or `Alt+.`. `.` says the current sentence.
- `,` (previous sentence): now `Alt+Up` or `Alt+,`. `,` says the current paragraph.
- `s` (say the sentence): now `.` or `Alt+Shift+S`. `s` moves to the next separator.
- `Shift+S` (say the paragraph): now `,`. `Shift+S` moves to the previous separator.
- `l` (say the line): now `Alt+Shift+L` (`Ctrl+L` in the GUI). `l` moves to the next list.
- `o` and `Shift+O` (next and previous list): now `l` and `Shift+L`. `o` does nothing.
- `Shift+H` (history back): now `Backspace` or `Alt+Left`. `Shift+H` moves to the previous heading.
- `Shift+L` (history forward): now `\\` or `Alt+Right`. `Shift+L` moves to the previous list.
- `k` (scroll up): now `Shift+J`. `k` moves to the next link.
- `Shift+K` (say the link address): now `Alt+Shift+K`. `Shift+K` moves to the previous link.
- `q` and `Shift+Q` (quit): now `Ctrl+Q` only, which still asks first. `q` moves to the next block quote.
- `Alt+Down` and `Alt+Up` (next and previous note): now `F12` and `Shift+F12`, or `e` and `Shift+E`. `Alt+Down` and `Alt+Up` move by sentence.
- `'` and `\"` (next and previous note): removed; use `e` and `Shift+E`.
- `Alt+Shift+D` (add a reference, terminal): now `Alt+B`, because Windows Terminal splits its window with `Alt+Shift+D`. The GUI keeps `Alt+Shift+D`.
- `Alt+Shift+Up` and `Alt+Shift+Down` (RSVP faster and slower) stay, and `Alt+Shift+PageUp` and `Alt+Shift+PageDown` do the same, because Windows Terminal resizes panes with the first two.

New keys: `g` and `Shift+G` (graphics), `d` and `Shift+D` (sections or chapters), `Ctrl+Down` and `Ctrl+Up` (paragraphs), `Alt+Shift+Q` (citations on or off while reading), `Alt+Shift+X` (explore math), `Alt+Shift+Z` (syllables), and `Alt+Shift+J` (difficult words). `p` and `Shift+P` still move by paragraph: NVDA's and JAWS's `p` is paragraph too. Say position stays on `Shift+W`.

## Quick navigation, as in NVDA and JAWS

In browse mode, a letter moves to the next item of a kind, and Shift with the letter to the previous one. textweaver follows NVDA's letters:

- `h`: heading. `1` to `6`: heading at that level.
- `l`: list. `i`: list item.
- `t`: table.
- `k`: link (`u` too).
- `q`: block quote.
- `s`: separator (a horizontal rule).
- `g`: graphic (an image).
- `d`: section or chapter, the nearest thing a document has to a landmark.
- `Backspace`: back to where you were before the last jump.

Where JAWS differs:

- JAWS moves between links with `u` (unvisited) and `v` (visited), and its `k` moves between place markers. In textweaver `u` also moves by link; place markers are bookmarks (`b`).
- JAWS's `q` moves to the main region, not a block quote.
- JAWS moves to a separator with the dash key. In textweaver the dash makes speech slower; use `s`.
- JAWS moves between regions (landmarks) with `r`, and its `d` moves to the next different element. In textweaver `r` reads the paragraph again; use `d` for sections.
- Sentences with `Alt+Down` and `Alt+Up`, and paragraphs with `Ctrl+Down` and `Ctrl+Up`, are JAWS's keys; NVDA uses the same paragraph keys.

## Help keys

- `?` in browse mode lists the keyboard shortcuts in both frontends; the GUI also opens that list with F3.
- F1 opens the help in both frontends.
- In the terminal, F3 is Find next and F4 Find previous, as in Star's terminal reader, so the terminal's keyboard list is on `?` only.

## Modes and layers

Every binding belongs to a layer. What a key does depends on the mode you are in:

| Mode | Layers searched, in order |
|---|---|
| Reading (browse) | browse, then global |
| Speech Cursor | speech cursor, then browse, then global |
| Editing | edit, then global; other keys type text |
| Find and command prompts | global only; the prompt takes the text you type |

Browse keys are single keys, like a screen reader's browse mode, and work the same in both frontends.
Global chords work in every mode. Speech Cursor keys take over browse keys with the same name while Speech Cursor is on (for example `j` reads the next line instead of scrolling).

In the tables below a key without a note is global; the others name their layer.
The GUI column shows Windows and Linux. The GUI on macOS column shows the Mac's own keys: Command for commands, Option with the arrows for words and paragraphs, Command with the arrows for the ends, and Command+Option for the chords that use Alt with a letter elsewhere, because Option with a letter types a character on a Mac.

## Single-key shortcuts

Browse keys are single printable keys. Speech recognition, dictation, and switch or scanning keyboards can type them by accident, so they can be turned off (WCAG 2.1.4, Character Key Shortcuts): press F9, run `toggle character keys` from the command palette, or set this in `settings.toml`:

```toml
[keyboard]
character_keys = false
```

While they are off, printable keys and Space never trigger commands in any mode; chords with Ctrl or Alt, the arrow and function keys, and the command palette (F2) keep working. Quitting and deleting a note or highlight always ask first (\"Quit textweaver? y or n\"), however you start them, so a stray `q` cannot close a document. The actions listed at the end of this page have only single keys; with single-key shortcuts off, run them from the command palette or give them a chord in `keymap.toml`.

## Changing keys

Put overrides in `keymap.toml` in the configuration directory. Each line replaces all of an action's keys; an empty list removes them:

```toml
next_sentence = [\"Alt+.\", \"x\"]
stop = [\"Escape\", \"b:Shift+Z\"]
bold = []
```

A key may name its layer with a prefix: `g:` global, `b:` browse, `s:` Speech Cursor, `e:` edit.
Without a prefix, a single character goes to the browse layer (so it never gets in the way of typing), and any other chord goes to the action's usual layer.
textweaver warns about unknown actions, keys it cannot read, and keys a terminal cannot send, and keeps going. A key your overrides would bind to two commands in one mode is not applied; the warning names it.

## Terminal notes

- Terminals cannot send `Ctrl+H` (it is Backspace), `Ctrl+I` (Tab), `Ctrl+M` or `Ctrl+J` (Enter), `Ctrl+Shift+` a letter (it arrives as `Ctrl+` the letter), or `Ctrl` with digits and most punctuation. The terminal defaults avoid all of them; the browse keys cover what the GUI does with those chords.
- F10 opens textweaver's menus. Some terminal programs keep F10 or F11 (full screen) for themselves; then run `menu` from the command palette (F2), and move by chapter with `Alt+PageDown` and `Alt+PageUp`.
- `Shift` with the arrow keys extends the selection in browse mode; most terminals send these keys, but some terminal programs keep `Shift+Up` and `Shift+Down` for scrolling their own window.
- `Alt` chords work in the terminal. Star's terminal reader lost them to the Escape key; textweaver reads them directly.
- The keys `1` to `6` move to the next heading of that level, and Shift with the digit to the previous one, as in a screen reader's browse mode. The tables show Shift with a digit as the character a US keyboard types (`!` `@` `#` `$` `%` `^`); textweaver matches the digit key itself, whatever your layout types. On Windows (Windows Terminal and the classic console) it reads the key from the console, so every layout works, including French AZERTY, where the digit row types `&` `é` `\"` without Shift. Elsewhere terminals send only the character, so textweaver knows the shifted digits of the US, UK, German, Spanish, Nordic, and Italian layouts (`\"` `£` `§` `·` `¤` and `&` as well as the US ones). French AZERTY types the digits only with Shift, so outside Windows set `digit_row = \"azerty\"` under `[keyboard]`: then `&` `é` `\"` `'` `(` `-` are the digit keys 1 to 6, and the digits typed with Shift go back.
";

/// `docs/keyboard.md`: every action by category, with its keys in both
/// frontends and the layer of each key.
pub fn keyboard_markdown() -> String {
    let term = Keymap::defaults(Platform::Linux, Frontend::Terminal);
    let gui = Keymap::defaults(Platform::Windows, Frontend::Gui);
    let mac = Keymap::defaults(Platform::MacOs, Frontend::Gui);
    let mut out = String::from(INTRO);
    for category in Category::ALL {
        let _ = write!(
            out,
            "\n## {}\n\n| Action | Terminal | GUI | GUI on macOS | Id |\n|---|---|---|---|---|\n",
            category.title()
        );
        for action in ActionId::in_category(category) {
            let _ = writeln!(
                out,
                "| {} | {} | {} | {} | `{}` |",
                action.help(),
                cell(action, &term.bindings_for(action)),
                cell(action, &gui.bindings_for(action)),
                mac_cell(action, &mac.bindings_for(action)),
                action.id()
            );
        }
    }
    out.push_str(&mac_terminal_markdown());
    out.push_str(&preset_markdown(Preset::Classic));
    let mut term_off = term.clone();
    term_off.set_character_keys(false);
    let mut gui_off = gui.clone();
    gui_off.set_character_keys(false);
    let (t_only, g_only) = (term_off.palette_only(), gui_off.palette_only());
    out.push_str(
        "\n## Command palette only, with single-key shortcuts off\n\n\
         These actions have only single-key shortcuts by default. With single-key shortcuts off, run them from the command palette (F2) or bind a chord in `keymap.toml`.\n\n\
         | Action | Terminal | GUI | Id |\n|---|---|---|---|\n",
    );
    for &action in ActionId::ALL.iter().filter(|a| !a.is_palette_command()) {
        let (t, g) = (t_only.contains(&action), g_only.contains(&action));
        if t || g {
            let mark = |b: bool| if b { "palette" } else { "has a chord" };
            let _ = writeln!(
                out,
                "| {} | {} | {} | `{}` |",
                action.help(),
                mark(t),
                mark(g),
                action.id()
            );
        }
    }
    out.push_str(
        "\n## Commands without keys\n\n\
         These commands have no keys by default. Run them from the command palette (F2, then type part of the name), or bind a key in `keymap.toml`.\n\n\
         | Action | Id |\n|---|---|\n",
    );
    for &action in ActionId::ALL.iter().filter(|a| a.is_palette_command()) {
        let _ = writeln!(out, "| {} | `{}` |", action.help(), action.id());
    }
    out
}

/// The section of `docs/keyboard.md` on the terminal's keys on macOS:
/// the few that differ, because macOS or VoiceOver keep the Windows ones.
fn mac_terminal_markdown() -> String {
    let term = Keymap::defaults(Platform::Linux, Frontend::Terminal);
    let mac = Keymap::defaults(Platform::MacOs, Frontend::Terminal);
    let mut out = String::from(
        "\n## The terminal on macOS\n\n\
         A terminal never passes the Command key, so on a Mac the terminal keeps the keys in the Terminal column, with Option as Alt (in Terminal, turn on \"Use Option as Meta key\"; in iTerm2, set the Option key to Esc+). These commands use other keys on a Mac, because VoiceOver keeps Ctrl+Option, Mission Control keeps Ctrl with the arrows, and macOS keeps Ctrl with F1 to F8 and Ctrl+Space:\n\n\
         | Action | Terminal | Terminal on macOS | Id |\n|---|---|---|---|\n",
    );
    for &action in ActionId::ALL {
        let (a, b) = (term.bindings_for(action), mac.bindings_for(action));
        if a != b {
            let _ = writeln!(
                out,
                "| {} | {} | {} | `{}` |",
                action.help(),
                cell(action, &a),
                mac_cell(action, &b),
                action.id()
            );
        }
    }
    out
}

/// The section of `docs/keyboard.md` for a preset: each key it changes,
/// what the key did before and does now, and where the displaced commands
/// went. Empty for the default preset.
pub fn preset_markdown(preset: Preset) -> String {
    if preset.changes().is_empty() {
        return String::new();
    }
    let term = Keymap::defaults(Platform::Linux, Frontend::Terminal);
    let changed = Keymap::with_preset(Platform::Linux, Frontend::Terminal, preset);
    let mut out = format!(
        "\n## The {id} preset\n\n\
         textweaver's single keys as they were before the default became the NVDA and JAWS layout: `.` and `,` move by sentence, `s` says the sentence and `l` the line, `Shift+H` and `Shift+L` go back and forward, `o` moves by list, and `q` quits (after asking). Choose it in `settings.toml`:\n\n\
         ```toml\n[keyboard]\npreset = \"{id}\"\n```\n\n\
         The old `screen-reader` preset is now the default, and `preset = \"screen-reader\"` still works: it means the default keys.\n\n\
         Your `keymap.toml` overrides apply on top of it. The tables above show the default keys; the preset changes only these, in both frontends:\n\n\
         | Key | Default keys | {id} preset |\n|---|---|---|\n",
        id = preset.id()
    );
    for (s, action) in preset.changes() {
        let (layer, chord) = s.split_once(':').unwrap_or(("b", s));
        let layer = Layer::from_prefix(layer).unwrap_or(Layer::Browse);
        let Ok(parsed) = chord.parse::<crate::KeyChord>() else {
            continue;
        };
        let before = term
            .bindings()
            .iter()
            .find(|b| b.chord == parsed && b.layer == layer)
            .map_or_else(|| "nothing".to_owned(), |b| b.action.help().to_owned());
        // A backslash needs no escape inside a code span.
        let key = parsed.to_string();
        let after = action.map_or("nothing", ActionId::help);
        let _ = writeln!(out, "| `{key}` ({}) | {before} | {after} |", layer.name());
    }
    let only = preset.palette_only();
    if !only.is_empty() {
        let names: Vec<String> = only.iter().map(|a| format!("`{}`", a.id())).collect();
        let _ = write!(
            out,
            "\nIn this preset {} have no keys: run them from the command palette, or bind keys in `keymap.toml`.\n",
            names.join(", ")
        );
    }
    out.push_str("\nWhere the default commands of those keys went, in the terminal:\n\n");
    let mut moved: Vec<ActionId> = Vec::new();
    for (s, _) in preset.changes() {
        let chord = s.split_once(':').map_or(*s, |(_, c)| c);
        if let Ok(parsed) = chord.parse::<crate::KeyChord>()
            && let Some(b) = term.bindings().iter().find(|b| b.chord == parsed)
            && !moved.contains(&b.action)
        {
            moved.push(b.action);
        }
    }
    for action in moved {
        let keys = changed.bindings_for(action);
        let where_now = if keys.is_empty() {
            "the command palette only".to_owned()
        } else {
            cell(action, &keys)
        };
        let _ = writeln!(out, "- {}: {where_now}.", action.help());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn help_lists_every_action_once() {
        let map = Keymap::defaults(Platform::Linux, Frontend::Terminal);
        let sections = map.help();
        assert_eq!(sections.len(), Category::ALL.len());
        let n: usize = sections.iter().map(|s| s.entries.len()).sum();
        assert_eq!(n, ActionId::ALL.len());
    }

    #[test]
    fn entry_text_and_speech() {
        let map = Keymap::defaults(Platform::Linux, Frontend::Terminal);
        let entry = HelpEntry {
            action: ActionId::NextSentence,
            bindings: map.bindings_for(ActionId::NextSentence),
        };
        assert_eq!(entry.keys_text(), "Alt+. or Alt+Down");
        assert_eq!(
            entry.spoken(),
            "Move to the next sentence: Alt period, or Alt Down Arrow."
        );
        let none = HelpEntry {
            action: ActionId::Stop,
            bindings: Vec::new(),
        };
        assert_eq!(none.keys_text(), "unbound");
    }

    #[test]
    fn markdown_has_every_action_and_escapes_pipes() {
        let md = keyboard_markdown();
        for a in ActionId::ALL {
            assert!(md.contains(&format!("`{}`", a.id())), "{a:?}");
        }
        assert!(md.contains("| Move to the next sentence | `Alt+.`, `Alt+Down` | `Alt+.`, `Alt+Down` | `Cmd+Option+.` | `next_sentence` |"), "{md}");
        assert!(md.contains("## The terminal on macOS"));
        assert!(md.contains("| Move to the next paragraph | `Ctrl+P`, `p` (browse), `]` (browse), `Ctrl+Down` (browse), `PageDown` (speech cursor) | `Ctrl+P`, `p` (browse), `]` (browse), `PageDown` (speech cursor) | `next_paragraph` |"), "{md}");
        assert!(md.contains("## What changed"));
        assert!(md.contains("## Quick navigation, as in NVDA and JAWS"));
        assert!(md.contains("`` Alt+` ``"));
    }

    #[test]
    fn markdown_documents_the_classic_preset() {
        let md = keyboard_markdown();
        assert!(md.contains("## The classic preset"), "{md}");
        assert!(md.contains("preset = \"classic\""));
        assert!(md.contains(
            "| `Shift+H` (browse) | Move to the previous heading without reading | Go back to where you were before the last jump |"
        ), "{md}");
        assert!(md.contains("| `k` (browse) | Move to the next link | Scroll up one line without moving the cursor |"));
        assert!(md.contains("| `g` (browse) | Move to the next graphic (image) | nothing |"));
        assert!(md.contains("`next_block_quote`, `previous_block_quote`"));
        assert!(preset_markdown(Preset::Default).is_empty());
    }
}
