//! Help generated from the keymap: the in-app keyboard help and
//! `docs/keyboard.md` (`cargo xtask keyboard`) come from the same data, so
//! they cannot disagree with the bindings.

use std::fmt::Write as _;

use crate::{ActionId, Binding, Category, Frontend, Keymap, Layer, Platform};

/// One action and its bindings.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HelpEntry {
    /// The action.
    pub action: ActionId,
    /// Its bindings, in definition order.
    pub bindings: Vec<Binding>,
}

impl HelpEntry {
    /// Keys as text, each with its layer unless global:
    /// `Alt+. or . (browse)`. "unbound" when there are none.
    pub fn keys_text(&self) -> String {
        if self.bindings.is_empty() {
            return "unbound".to_owned();
        }
        self.bindings
            .iter()
            .map(|b| match b.layer {
                Layer::Global => b.chord.to_string(),
                l => format!("{} ({})", b.chord, l.name()),
            })
            .collect::<Vec<_>>()
            .join(" or ")
    }

    /// The entry as one sentence for speech: "Move to the next sentence:
    /// Alt period, or period in browse mode."
    pub fn spoken(&self) -> String {
        if self.bindings.is_empty() {
            return format!("{}: no key.", self.action.help());
        }
        let keys: Vec<String> = self
            .bindings
            .iter()
            .map(|b| match b.layer {
                Layer::Global => b.chord.spoken(),
                l => format!("{} in {} mode", b.chord.spoken(), l.name()),
            })
            .collect();
        format!("{}: {}.", self.action.help(), keys.join(", or "))
    }
}

/// The actions of one category.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HelpSection {
    /// The category.
    pub category: Category,
    /// Its actions, in help order.
    pub entries: Vec<HelpEntry>,
}

impl Keymap {
    /// Help for this keymap (defaults plus the user's overrides), grouped
    /// by category in help order. Every action is listed, bound or not.
    pub fn help(&self) -> Vec<HelpSection> {
        Category::ALL
            .iter()
            .map(|&category| HelpSection {
                category,
                entries: ActionId::in_category(category)
                    .map(|action| HelpEntry {
                        action,
                        bindings: self.bindings_for(action),
                    })
                    .collect(),
            })
            .collect()
    }
}

fn cell(bindings: &[Binding]) -> String {
    if bindings.is_empty() {
        return "none".to_owned();
    }
    bindings
        .iter()
        .map(|b| {
            let chord = b.chord.to_string();
            // Backticks inside a code span need a longer fence.
            let code = if chord.contains('`') {
                format!("`` {chord} ``")
            } else {
                format!("`{chord}`")
            };
            match b.layer {
                Layer::Global => code,
                l => format!("{code} ({})", l.name()),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
        .replace('|', "\\|")
}

const INTRO: &str = "\
# Keyboard reference

Generated by `cargo xtask keyboard` from `crates/textweaver-keymap`; do not edit by hand.
The in-app keyboard help shows the same table with your own overrides applied.

## Help keys

- `?` in browse mode lists the keyboard shortcuts in both frontends; the GUI also opens that list with F3.
- F1 opens the help in both frontends.
- In the terminal, F3 is Find next and F4 Find previous, as in Star's terminal reader, so the terminal's keyboard list is on `?` only.

## Modes and layers

Every binding belongs to a layer. What a key does depends on the mode you are in:

| Mode | Layers searched, in order |
|---|---|
| Reading (browse) | browse, then global |
| Speech Cursor | speech cursor, then browse, then global |
| Editing | edit, then global; other keys type text |
| Find and command prompts | global only; the prompt takes the text you type |

Browse keys are single keys, like a screen reader's browse mode, and work the same in both frontends.
Global chords work in every mode. Speech Cursor keys take over browse keys with the same name while Speech Cursor is on (for example `j` reads the next line instead of scrolling).

In the tables below a key without a note is global; the others name their layer.
The GUI column shows Windows and Linux; on macOS the GUI uses Cmd wherever it shows Ctrl.

## Single-key shortcuts

Browse keys are single printable keys. Speech recognition, dictation, and switch or scanning keyboards can type them by accident, so they can be turned off (WCAG 2.1.4, Character Key Shortcuts): press F9, run `toggle character keys` from the command palette, or set this in `settings.toml`:

```toml
[keyboard]
character_keys = false
```

While they are off, printable keys and Space never trigger commands in any mode; chords with Ctrl or Alt, the arrow and function keys, and the command palette (F2) keep working. Quitting and deleting a note or highlight always ask first (\"Quit textweaver? y or n\"), however you start them, so a stray `q` cannot close a document. The actions listed at the end of this page have only single keys; with single-key shortcuts off, run them from the command palette or give them a chord in `keymap.toml`.

## Changing keys

Put overrides in `keymap.toml` in the configuration directory. Each line replaces all of an action's keys; an empty list removes them:

```toml
next_sentence = [\"Alt+.\", \".\"]
stop = [\"Escape\", \"b:x\"]
bold = []
```

A key may name its layer with a prefix: `g:` global, `b:` browse, `s:` Speech Cursor, `e:` edit.
Without a prefix, a single character goes to the browse layer (so it never gets in the way of typing), and any other chord goes to the action's usual layer.
textweaver warns about unknown actions, keys it cannot read, and keys a terminal cannot send, and keeps going. A key your overrides would bind to two commands in one mode is not applied; the warning names it.

## Terminal notes

- Terminals cannot send `Ctrl+H` (it is Backspace), `Ctrl+I` (Tab), `Ctrl+M` or `Ctrl+J` (Enter), `Ctrl+Shift+` a letter (it arrives as `Ctrl+` the letter), or `Ctrl` with digits and most punctuation. The terminal defaults avoid all of them; the browse keys cover what the GUI does with those chords.
- Some terminal programs keep F10 (menu) or F11 (full screen) for themselves. Chapters also move with `Alt+PageDown` and `Alt+PageUp`.
- `Shift` with the arrow keys extends the selection in browse mode; most terminals send these keys, but some terminal programs keep `Shift+Up` and `Shift+Down` for scrolling their own window.
- `Alt` chords work in the terminal. Star's terminal reader lost them to the Escape key; textweaver reads them directly.
";

/// `docs/keyboard.md`: every action by category, with its keys in both
/// frontends and the layer of each key.
pub fn keyboard_markdown() -> String {
    let term = Keymap::defaults(Platform::Linux, Frontend::Terminal);
    let gui = Keymap::defaults(Platform::Windows, Frontend::Gui);
    let mut out = String::from(INTRO);
    for category in Category::ALL {
        let _ = write!(
            out,
            "\n## {}\n\n| Action | Terminal | GUI | Id |\n|---|---|---|---|\n",
            category.title()
        );
        for action in ActionId::in_category(category) {
            let _ = writeln!(
                out,
                "| {} | {} | {} | `{}` |",
                action.help(),
                cell(&term.bindings_for(action)),
                cell(&gui.bindings_for(action)),
                action.id()
            );
        }
    }
    let mut term_off = term.clone();
    term_off.set_character_keys(false);
    let mut gui_off = gui.clone();
    gui_off.set_character_keys(false);
    let (t_only, g_only) = (term_off.palette_only(), gui_off.palette_only());
    out.push_str(
        "\n## Command palette only, with single-key shortcuts off\n\n\
         These actions have only single-key shortcuts by default. With single-key shortcuts off, run them from the command palette (F2) or bind a chord in `keymap.toml`.\n\n\
         | Action | Terminal | GUI | Id |\n|---|---|---|---|\n",
    );
    for &action in ActionId::ALL {
        let (t, g) = (t_only.contains(&action), g_only.contains(&action));
        if t || g {
            let mark = |b: bool| if b { "palette" } else { "has a chord" };
            let _ = writeln!(
                out,
                "| {} | {} | {} | `{}` |",
                action.help(),
                mark(t),
                mark(g),
                action.id()
            );
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn help_lists_every_action_once() {
        let map = Keymap::defaults(Platform::Linux, Frontend::Terminal);
        let sections = map.help();
        assert_eq!(sections.len(), Category::ALL.len());
        let n: usize = sections.iter().map(|s| s.entries.len()).sum();
        assert_eq!(n, ActionId::ALL.len());
    }

    #[test]
    fn entry_text_and_speech() {
        let map = Keymap::defaults(Platform::Linux, Frontend::Terminal);
        let entry = HelpEntry {
            action: ActionId::NextSentence,
            bindings: map.bindings_for(ActionId::NextSentence),
        };
        assert_eq!(entry.keys_text(), "Alt+. or . (browse)");
        assert_eq!(
            entry.spoken(),
            "Move to the next sentence: Alt period, or period in browse mode."
        );
        let none = HelpEntry {
            action: ActionId::Stop,
            bindings: Vec::new(),
        };
        assert_eq!(none.keys_text(), "unbound");
    }

    #[test]
    fn markdown_has_every_action_and_escapes_pipes() {
        let md = keyboard_markdown();
        for a in ActionId::ALL {
            assert!(md.contains(&format!("`{}`", a.id())), "{a:?}");
        }
        assert!(md.contains("| Move to the next sentence | `Alt+.`, `.` (browse) | `Alt+.`, `.` (browse) | `next_sentence` |"));
        assert!(md.contains("`` Alt+` ``"));
    }
}
