//! Documentation checks.
//!
//! - `cargo xtask settings-doc [--check]`: regenerates
//!   `docs/settings-reference.md` from the settings schema, or with
//!   `--check` fails when it is out of date. The renderer lives next to the
//!   schema, in `crates/textweaver-app/tests/it/settings_reference.rs`; this
//!   runs that test, with `TEXTWEAVER_UPDATE_DOCS=1` when it should write.
//! - `cargo xtask docs --check`: the indexes match the tree. The ADR index
//!   (`docs/adr/README.md`) lists every ADR once, in number order, and no
//!   two ADR files share a number; the Decisions list in `docs/README.md`
//!   matches the index; the crate count in `docs/README.md` and
//!   `docs/dev/architecture.md` matches `crates/`; every guide in
//!   `docs/*.md` ends with a "See also" section and is linked from
//!   `docs/README.md`; and US English: no British spelling from
//!   [`BRITISH`] in the English messages (`en.ftl`, values only), `README.md`,
//!   `CONTRIBUTING.md`, or `docs/` (outside the history and research
//!   records, code, and link targets). The user guides (`docs/*.md`, not
//!   `docs/dev`) name releases, not internal waves or dates ([`dated_words`]);
//!   a theme count in `docs/README.md` matches the theme files; and every
//!   image has alternative text and a "Description:" line near it
//!   ([`image_problems`]). Each problem is one line naming the file and the
//!   fact.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::Context;

/// Guides generated by other tools, which end the way their generator
/// writes them.
const GENERATED: &[&str] = &["keyboard.md"];

/// British spellings and their US forms, for the US English check. Variant
/// spellings US dictionaries also list ("cancelled", "labelled") are not
/// here.
const BRITISH: &[(&str, &str)] = &[
    ("behaviour", "behavior"),
    ("behaviours", "behaviors"),
    ("catalogue", "catalog"),
    ("catalogues", "catalogs"),
    ("centre", "center"),
    ("centred", "centered"),
    ("centres", "centers"),
    ("colour", "color"),
    ("coloured", "colored"),
    ("colours", "colors"),
    ("favourite", "favorite"),
    ("favourites", "favorites"),
    ("grey", "gray"),
    ("greyscale", "grayscale"),
    ("honour", "honor"),
    ("honours", "honors"),
    ("licence", "license"),
    ("licences", "licenses"),
    ("organise", "organize"),
    ("organised", "organized"),
    ("practise", "practice"),
    ("recentre", "recenter"),
    ("recentres", "recenters"),
    ("recognise", "recognize"),
    ("recognised", "recognized"),
    ("recognises", "recognizes"),
];

/// Folders under `docs/` that are records, quoted as written: the
/// history and the research reports.
const RECORDS: &[&str] = &["docs/history/", "docs/dev/research/"];

/// The repository root.
fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."))
}

/// `cargo xtask settings-doc [--check]`.
pub fn settings_doc() -> anyhow::Result<()> {
    let check = std::env::args().skip(2).any(|a| a == "--check");
    let ok = run_settings_test(check)?;
    if check {
        anyhow::ensure!(
            ok,
            "docs/settings-reference.md is out of date; run `cargo xtask settings-doc`"
        );
        println!("docs/settings-reference.md is up to date");
    } else {
        anyhow::ensure!(ok, "writing docs/settings-reference.md failed");
        println!("wrote docs/settings-reference.md");
    }
    Ok(())
}

/// Runs the `settings_reference` module of the app crate's test program,
/// which checks `docs/settings-reference.md` or, unless `check`, rewrites
/// it. True when the test passed. It builds the app crate, so a build failure also reads
/// as false.
pub fn run_settings_test(check: bool) -> anyhow::Result<bool> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut cmd = Command::new(cargo);
    cmd.current_dir(root()).args([
        "test",
        "--quiet",
        "-p",
        "textweaver-app",
        "--test",
        "it",
        "--",
        "settings_reference::",
    ]);
    if check {
        cmd.env_remove("TEXTWEAVER_UPDATE_DOCS");
    } else {
        cmd.env("TEXTWEAVER_UPDATE_DOCS", "1");
    }
    let status = cmd.status().context("running cargo test")?;
    Ok(status.success())
}

/// The files that state the crate count, and the words around the number.
const CRATE_COUNTS: [(&str, &str, &str); 2] = [
    ("docs/README.md", "each of the ", " crates"),
    ("docs/dev/architecture.md", "workspace with ", " crates"),
];

/// The number of crates in `crates/`.
fn crate_count(root: &Path) -> anyhow::Result<usize> {
    Ok(file_names(&root.join("crates"))?
        .into_iter()
        .filter(|c| root.join("crates").join(c).join("Cargo.toml").is_file())
        .count())
}

/// Rewrites the crate counts in the docs to match `crates/`, and returns
/// the files it changed. The rest of what `docs --check` checks (the ADR
/// lists, the See also sections, the index links) is written by hand.
pub fn write_crate_counts(root: &Path) -> anyhow::Result<Vec<String>> {
    let crates = crate_count(root)?;
    let mut changed = Vec::new();
    for (file, before, after) in CRATE_COUNTS {
        let path = root.join(file);
        let text = std::fs::read_to_string(&path).with_context(|| format!("reading {file}"))?;
        if let Some(new) = replace_number_between(&text, before, after, crates)
            && new != text
        {
            std::fs::write(&path, new).with_context(|| format!("writing {file}"))?;
            changed.push(file.to_owned());
        }
    }
    Ok(changed)
}

/// `cargo xtask docs --check`.
pub fn run() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(2).collect();
    anyhow::ensure!(
        args.iter().any(|a| a == "--check"),
        "usage: cargo xtask docs --check"
    );
    let problems = check(&root())?;
    if problems.is_empty() {
        println!("docs: the indexes, crate counts, See also sections, and US spelling are current");
        return Ok(());
    }
    for p in &problems {
        eprintln!("{p}");
    }
    let n = problems.len();
    anyhow::bail!("docs: {n} {}", if n == 1 { "problem" } else { "problems" })
}

/// Every problem found under `root`, one line each.
pub fn check(root: &Path) -> anyhow::Result<Vec<String>> {
    let mut problems = Vec::new();
    let read = |rel: &str| -> anyhow::Result<String> {
        std::fs::read_to_string(root.join(rel))
            .map(|s| s.replace("\r\n", "\n"))
            .with_context(|| format!("reading {rel}"))
    };

    // The ADR files.
    let mut adrs: Vec<(u32, String)> = Vec::new();
    for name in file_names(&root.join("docs/adr"))? {
        if let Some(n) = adr_number(&name) {
            adrs.push((n, name));
        }
    }
    adrs.sort();
    for pair in adrs.windows(2) {
        if pair[0].0 == pair[1].0 {
            problems.push(format!(
                "docs/adr: {} and {} share the number {:04}",
                pair[0].1, pair[1].1, pair[0].0
            ));
        }
    }

    // The ADR index.
    let index = read("docs/adr/README.md")?;
    let listed = adr_links(&index, "");
    compare_adr_list("docs/adr/README.md", &listed, &adrs, &mut problems);

    // The Decisions list in the documentation index.
    let docs_index = read("docs/README.md")?;
    let decisions = section(&docs_index, "## Decisions");
    let listed = adr_links(decisions, "adr/");
    compare_adr_list("docs/README.md, Decisions", &listed, &adrs, &mut problems);

    // The crate count.
    let crates = crate_count(root)?;
    for (file, before, after) in CRATE_COUNTS {
        let text = read(file)?;
        match number_between(&text, before, after) {
            Some(n) if n == crates => {}
            Some(n) => problems.push(format!("{file}: says {n} crates, but crates/ has {crates}")),
            None => problems.push(format!(
                "{file}: no crate count (\"{before}N{after}\") found"
            )),
        }
    }

    // US English.
    let mut texts = vec!["README.md".to_owned(), "CONTRIBUTING.md".to_owned()];
    markdown_under(root, "docs", &mut texts)?;
    for rel in texts {
        if !RECORDS.iter().any(|r| rel.starts_with(r)) {
            problems.extend(british_spellings(&rel, &read(&rel)?, false));
        }
    }
    let ftl = "crates/textweaver-lexicon/locales/en.ftl";
    problems.extend(british_spellings(ftl, &read(ftl)?, true));

    // The guides.
    for name in file_names(&root.join("docs"))? {
        if !name.ends_with(".md") || name == "README.md" {
            continue;
        }
        let text = read(&format!("docs/{name}"))?;
        if !GENERATED.contains(&name.as_str()) {
            let last = text.lines().rev().find(|l| l.starts_with("## "));
            if last != Some("## See also") {
                problems.push(format!(
                    "docs/{name}: does not end with a \"See also\" section"
                ));
            }
        }
        if !docs_index.contains(&format!("]({name})"))
            && !docs_index.contains(&format!("]({name}#"))
        {
            problems.push(format!("docs/{name}: not linked from docs/README.md"));
        }
        // A user guide names the release, never a wave or a date.
        if !GENERATED.contains(&name.as_str()) {
            problems.extend(dated_words(&format!("docs/{name}"), &text));
        }
    }

    // The theme count, where the index states one.
    let themes = file_names(&root.join("crates/textweaver-theme/themes"))?
        .into_iter()
        .filter(|n| n.ends_with(".toml"))
        .count();
    if let Some(n) = number_between(&docs_index, "the ", " built-in color themes")
        && n != themes
    {
        problems.push(format!(
            "docs/README.md: says {n} built-in themes, but crates/textweaver-theme/themes has {themes}"
        ));
    }

    // Images: alternative text, and a description in words beside them.
    let mut pages = vec!["README.md".to_owned()];
    markdown_under(root, "docs", &mut pages)?;
    for rel in pages {
        if !RECORDS.iter().any(|r| rel.starts_with(r)) {
            problems.extend(image_problems(&rel, &read(&rel)?));
        }
    }
    Ok(problems)
}

const MONTHS: [&str; 12] = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
];

/// Internal names and dates in a user guide, one problem line each: "Wave"
/// and a number, "this alpha", and "since" or "on" before a month and a
/// day. Fenced code and code spans are skipped.
fn dated_words(rel: &str, text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut fenced = false;
    for (i, line) in text.lines().enumerate() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        let prose = without_code_spans(line);
        let words: Vec<&str> = prose
            .split(|c: char| !c.is_alphanumeric())
            .filter(|w| !w.is_empty())
            .collect();
        for (j, w) in words.iter().enumerate() {
            let next = words.get(j + 1).copied().unwrap_or("");
            let after = words.get(j + 2).copied().unwrap_or("");
            let fact = if *w == "Wave" && next.starts_with(|c: char| c.is_ascii_digit()) {
                Some(format!("\"Wave {next}\"; name the release instead"))
            } else if w.eq_ignore_ascii_case("this") && next == "alpha" {
                Some("\"this alpha\"; name the release instead".to_owned())
            } else if (w.eq_ignore_ascii_case("since") || w.eq_ignore_ascii_case("on"))
                && MONTHS.contains(&next)
                && after.starts_with(|c: char| c.is_ascii_digit())
            {
                Some(format!(
                    "\"{w} {next} {after}\"; name the release instead of a date"
                ))
            } else {
                None
            };
            if let Some(f) = fact {
                out.push(format!("{rel}:{}: {f}", i + 1));
            }
        }
    }
    out
}

/// `line` with its code spans blanked out.
fn without_code_spans(line: &str) -> String {
    let mut out = String::with_capacity(line.len());
    let mut code = false;
    for c in line.chars() {
        if c == '`' {
            code = !code;
            out.push(' ');
        } else {
            out.push(if code { ' ' } else { c });
        }
    }
    out
}

/// Images in Markdown (`![alt](file)`, outside code) with no alternative
/// text, or with no line starting "Description:" within three lines, so a
/// screen reader user learns what the picture shows.
fn image_problems(rel: &str, text: &str) -> Vec<String> {
    let lines: Vec<&str> = text.lines().collect();
    let mut out = Vec::new();
    let mut fenced = false;
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        let prose = without_code_spans(line);
        let mut rest = prose.as_str();
        while let Some(at) = rest.find("![") {
            let after = &rest[at + 2..];
            let Some(close) = after.find("](") else {
                break;
            };
            if after[..close].trim().is_empty() {
                out.push(format!(
                    "{rel}:{}: an image with no alternative text",
                    i + 1
                ));
            }
            let from = i.saturating_sub(3);
            let near = lines
                .iter()
                .skip(from)
                .take(i + 4 - from)
                .any(|l| l.trim_start().starts_with("Description:"));
            if !near {
                out.push(format!(
                    "{rel}:{}: an image with no \"Description:\" line within 3 lines",
                    i + 1
                ));
            }
            rest = &after[close..];
        }
    }
    out
}

/// Every Markdown file under `rel` (relative to `root`), as `/`-separated
/// paths relative to `root`, appended to `out` in sorted order.
fn markdown_under(root: &Path, rel: &str, out: &mut Vec<String>) -> anyhow::Result<()> {
    for name in file_names(&root.join(rel))? {
        let child = format!("{rel}/{name}");
        if root.join(&child).is_dir() {
            markdown_under(root, &child, out)?;
        } else if name.ends_with(".md") {
            out.push(child);
        }
    }
    Ok(())
}

/// The British spellings in `text` (the file `rel`), one problem line
/// each: "docs/x.md:3: colour; write color". Fenced code, code spans,
/// link targets, and (in a Fluent file) message ids, comments, and
/// placeables are skipped, and so is a word joined to an id by `-` or
/// named as a variable with `$`.
fn british_spellings(rel: &str, text: &str, ftl: bool) -> Vec<String> {
    let mut out = Vec::new();
    let mut fenced = false;
    for (i, line) in text.lines().enumerate() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        let prose = if ftl {
            if trimmed.starts_with('#') {
                continue;
            }
            match line.split_once('=') {
                Some((id, value)) if !id.starts_with(' ') && !id.trim().contains(' ') => value,
                _ if line.starts_with(' ') => line,
                _ => continue,
            }
        } else {
            line
        };
        for word in prose_words(prose) {
            let lower = word.to_lowercase();
            if let Some((_, us)) = BRITISH.iter().find(|(gb, _)| *gb == lower) {
                out.push(format!("{rel}:{}: {word}; write {us}", i + 1));
            }
        }
    }
    out
}

/// The words of `line` outside code spans, link targets (`](...)`), and
/// Fluent placeables (`{ ... }`). A word is a run of letters; one joined
/// to `-`, `_`, `$`, or a digit is part of a name and is skipped.
fn prose_words(line: &str) -> Vec<&str> {
    let bytes = line.as_bytes();
    let mut spans: Vec<(usize, usize)> = Vec::new();
    let mut i = 0;
    let mut start: Option<usize> = None;
    while i < bytes.len() {
        let b = bytes[i];
        if b.is_ascii_alphabetic() {
            start.get_or_insert(i);
            i += 1;
            continue;
        }
        if let Some(s) = start.take() {
            spans.push((s, i));
        }
        let skip_to = match b {
            b'`' => line[i + 1..].find('`').map(|j| i + 1 + j),
            b'{' => line[i + 1..].find('}').map(|j| i + 1 + j),
            b']' if bytes.get(i + 1) == Some(&b'(') => line[i + 1..].find(')').map(|j| i + 1 + j),
            _ => None,
        };
        i = skip_to.map_or(i + 1, |j| j + 1);
    }
    if let Some(s) = start {
        spans.push((s, bytes.len()));
    }
    let joined = |b: u8| b == b'-' || b == b'_' || b == b'$' || b.is_ascii_digit();
    spans
        .into_iter()
        .filter(|&(s, e)| {
            let before = s.checked_sub(1).map(|j| bytes[j]);
            !before.is_some_and(joined) && !bytes.get(e).copied().is_some_and(joined)
        })
        .map(|(s, e)| &line[s..e])
        .collect()
}

/// The file names in `dir`, sorted.
fn file_names(dir: &Path) -> anyhow::Result<Vec<String>> {
    let mut out: Vec<String> = std::fs::read_dir(dir)
        .with_context(|| format!("listing {}", dir.display()))?
        .filter_map(Result::ok)
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    out.sort();
    Ok(out)
}

/// 17 for `0017-writers.md`.
fn adr_number(name: &str) -> Option<u32> {
    let (num, rest) = name.split_once('-')?;
    (num.len() == 4 && rest.ends_with(".md"))
        .then(|| num.parse().ok())
        .flatten()
}

/// The text from the heading `heading` to the next level-2 heading.
fn section<'a>(text: &'a str, heading: &str) -> &'a str {
    let Some(start) = text.find(&format!("\n{heading}\n")) else {
        return "";
    };
    let body = &text[start + heading.len() + 2..];
    match body.find("\n## ") {
        Some(end) => &body[..end],
        None => body,
    }
}

/// The ADRs a list links to, in order: the number the link text gives, and
/// the file it links to (with `prefix` removed).
fn adr_links(text: &str, prefix: &str) -> Vec<(u32, String)> {
    let mut out = Vec::new();
    for line in text.lines() {
        let Some(rest) = line.strip_prefix("- [ADR-") else {
            continue;
        };
        let Some(n) = rest.get(..4).and_then(|d| d.parse().ok()) else {
            continue;
        };
        let target = line
            .split_once("](")
            .and_then(|(_, t)| t.split_once(')'))
            .map(|(t, _)| t.strip_prefix(prefix).unwrap_or(t).to_owned())
            .unwrap_or_default();
        out.push((n, target));
    }
    out
}

fn compare_adr_list(
    what: &str,
    listed: &[(u32, String)],
    files: &[(u32, String)],
    problems: &mut Vec<String>,
) {
    for (n, name) in files {
        match listed.iter().filter(|(m, _)| m == n).count() {
            0 => problems.push(format!("{what}: ADR-{n:04} ({name}) is missing")),
            1 => {}
            k => problems.push(format!("{what}: ADR-{n:04} is listed {k} times")),
        }
    }
    for (n, target) in listed {
        match files.iter().find(|(m, _)| m == n) {
            None => problems.push(format!("{what}: ADR-{n:04} has no file in docs/adr")),
            Some((_, name)) if name != target => problems.push(format!(
                "{what}: ADR-{n:04} links to {target}, but the file is {name}"
            )),
            Some(_) => {}
        }
    }
    for pair in listed.windows(2) {
        if pair[1].0 < pair[0].0 {
            problems.push(format!(
                "{what}: ADR-{:04} comes after ADR-{:04}; list them in number order",
                pair[1].0, pair[0].0
            ));
        }
    }
}

/// The number written between `before` and `after`, such as 33 in
/// "each of the 33 crates".
fn number_between(text: &str, before: &str, after: &str) -> Option<usize> {
    text.match_indices(before).find_map(|(i, _)| {
        let rest = &text[i + before.len()..];
        let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
        (!digits.is_empty() && rest[digits.len()..].starts_with(after))
            .then(|| digits.parse().ok())
            .flatten()
    })
}

/// `text` with the first number written between `before` and `after`
/// replaced by `n`, or `None` when there is no such number.
fn replace_number_between(text: &str, before: &str, after: &str, n: usize) -> Option<String> {
    text.match_indices(before).find_map(|(i, _)| {
        let start = i + before.len();
        let rest = &text[start..];
        let len = rest.chars().take_while(char::is_ascii_digit).count();
        (len > 0 && rest[len..].starts_with(after))
            .then(|| format!("{}{n}{}", &text[..start], &rest[len..]))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_docs_are_current() {
        let problems = check(&root()).expect("the docs are readable");
        assert!(problems.is_empty(), "{}", problems.join("\n"));
    }

    #[test]
    fn adr_lists_are_compared() {
        let files = vec![(1, "0001-a.md".to_owned()), (2, "0002-b.md".to_owned())];
        let mut p = Vec::new();
        compare_adr_list(
            "index",
            &[(2, "0002-b.md".into()), (1, "0001-x.md".into())],
            &files,
            &mut p,
        );
        assert_eq!(
            p,
            vec![
                "index: ADR-0001 links to 0001-x.md, but the file is 0001-a.md",
                "index: ADR-0001 comes after ADR-0002; list them in number order",
            ]
        );
        let mut p = Vec::new();
        compare_adr_list("index", &[(1, "0001-a.md".into())], &files, &mut p);
        assert_eq!(p, vec!["index: ADR-0002 (0002-b.md) is missing"]);
    }

    #[test]
    fn british_spellings_are_found_outside_code_and_names() {
        let md = "A colour.
`colour` and [x](colour.md) and a-colour
```
colour
```
Centres, Licence.";
        assert_eq!(
            british_spellings("x.md", md, false),
            vec![
                "x.md:1: colour; write color",
                "x.md:6: Centres; write centers",
                "x.md:6: Licence; write license",
            ]
        );
        let ftl = "# the licence
voices-licence-x = { $licence } licence
    grey here
";
        assert_eq!(
            british_spellings("en.ftl", ftl, true),
            vec![
                "en.ftl:2: licence; write license",
                "en.ftl:3: grey; write gray",
            ]
        );
        assert!(british_spellings("x.md", "color, license, cancelled", false).is_empty());
    }

    #[test]
    fn user_guides_name_releases_not_waves_or_dates() {
        let md = "Since Wave 5, F10 opens menus.
New in this alpha.
It changed on September 26, 2026.
`Wave 3` in code, and the 0.1.0-alpha.4 release, are fine.
```
Wave 2
```";
        assert_eq!(
            dated_words("docs/x.md", md),
            vec![
                "docs/x.md:1: \"Wave 5\"; name the release instead",
                "docs/x.md:2: \"this alpha\"; name the release instead",
                "docs/x.md:3: \"on September 26\"; name the release instead of a date",
            ]
        );
    }

    #[test]
    fn images_need_alternative_text_and_a_description() {
        let md = "![](a.png)




                  ![The window in Galaxy](b.png)
                  Description: the document with the spoken word bold.




                  ![Settings](c.png)

                  `![code](d.png)` is not an image.";
        assert_eq!(
            image_problems("x.md", md),
            vec![
                "x.md:1: an image with no alternative text",
                "x.md:1: an image with no \"Description:\" line within 3 lines",
                "x.md:12: an image with no \"Description:\" line within 3 lines",
            ]
        );
    }

    #[test]
    fn numbers_and_links_are_read() {
        assert_eq!(adr_number("0017-writers.md"), Some(17));
        assert_eq!(adr_number("README.md"), None);
        assert_eq!(
            number_between("what each of the 33 crates does", "each of the ", " crates"),
            Some(33)
        );
        assert_eq!(
            adr_links("- [ADR-0017: Writers](adr/0017-writers.md): text", "adr/"),
            vec![(17, "0017-writers.md".to_owned())]
        );
        assert_eq!(
            replace_number_between(
                "each of the 3 things; each of the 33 crates, all 33",
                "each of the ",
                " crates",
                34
            )
            .as_deref(),
            Some("each of the 3 things; each of the 34 crates, all 33")
        );
        assert_eq!(
            replace_number_between("no count", "the ", " crates", 1),
            None
        );
        assert_eq!(
            section("a\n## Decisions\nx\ny\n## Next\nz", "## Decisions"),
            "x\ny"
        );
    }
}
