//! Documentation checks.
//!
//! - `cargo xtask settings-doc [--check]`: regenerates
//!   `docs/settings-reference.md` from the settings schema, or with
//!   `--check` fails when it is out of date. The renderer lives next to the
//!   schema, in `crates/textweaver-app/tests/settings_reference.rs`; this
//!   runs that test, with `TEXTWEAVER_UPDATE_DOCS=1` when it should write.
//! - `cargo xtask docs --check`: the indexes match the tree. The ADR index
//!   (`docs/adr/README.md`) lists every ADR once, in number order, and no
//!   two ADR files share a number; the Decisions list in `docs/README.md`
//!   matches the index; the crate count in `docs/README.md` and
//!   `docs/dev/architecture.md` matches `crates/`; every guide in
//!   `docs/*.md` ends with a "See also" section and is linked from
//!   `docs/README.md`. Each problem is one line naming the file and the
//!   fact.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::Context;

/// Guides generated by other tools, which end the way their generator
/// writes them.
const GENERATED: &[&str] = &["keyboard.md"];

/// The repository root.
fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."))
}

/// `cargo xtask settings-doc [--check]`.
pub fn settings_doc() -> anyhow::Result<()> {
    let check = std::env::args().skip(2).any(|a| a == "--check");
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut cmd = Command::new(cargo);
    cmd.current_dir(root()).args([
        "test",
        "--quiet",
        "-p",
        "textweaver-app",
        "--test",
        "settings_reference",
    ]);
    if check {
        cmd.env_remove("TEXTWEAVER_UPDATE_DOCS");
    } else {
        cmd.env("TEXTWEAVER_UPDATE_DOCS", "1");
    }
    let status = cmd.status().context("running cargo test")?;
    if check {
        anyhow::ensure!(
            status.success(),
            "docs/settings-reference.md is out of date; run `cargo xtask settings-doc`"
        );
        println!("docs/settings-reference.md is up to date");
    } else {
        anyhow::ensure!(
            status.success(),
            "writing docs/settings-reference.md failed"
        );
        println!("wrote docs/settings-reference.md");
    }
    Ok(())
}

/// `cargo xtask docs --check`.
pub fn run() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(2).collect();
    anyhow::ensure!(
        args.iter().any(|a| a == "--check"),
        "usage: cargo xtask docs --check"
    );
    let problems = check(&root())?;
    if problems.is_empty() {
        println!("docs: the indexes, crate counts, and See also sections are current");
        return Ok(());
    }
    for p in &problems {
        eprintln!("{p}");
    }
    let n = problems.len();
    anyhow::bail!("docs: {n} {}", if n == 1 { "problem" } else { "problems" })
}

/// Every problem found under `root`, one line each.
pub fn check(root: &Path) -> anyhow::Result<Vec<String>> {
    let mut problems = Vec::new();
    let read = |rel: &str| -> anyhow::Result<String> {
        std::fs::read_to_string(root.join(rel))
            .map(|s| s.replace("\r\n", "\n"))
            .with_context(|| format!("reading {rel}"))
    };

    // The ADR files.
    let mut adrs: Vec<(u32, String)> = Vec::new();
    for name in file_names(&root.join("docs/adr"))? {
        if let Some(n) = adr_number(&name) {
            adrs.push((n, name));
        }
    }
    adrs.sort();
    for pair in adrs.windows(2) {
        if pair[0].0 == pair[1].0 {
            problems.push(format!(
                "docs/adr: {} and {} share the number {:04}",
                pair[0].1, pair[1].1, pair[0].0
            ));
        }
    }

    // The ADR index.
    let index = read("docs/adr/README.md")?;
    let listed = adr_links(&index, "");
    compare_adr_list("docs/adr/README.md", &listed, &adrs, &mut problems);

    // The Decisions list in the documentation index.
    let docs_index = read("docs/README.md")?;
    let decisions = section(&docs_index, "## Decisions");
    let listed = adr_links(decisions, "adr/");
    compare_adr_list("docs/README.md, Decisions", &listed, &adrs, &mut problems);

    // The crate count.
    let crates = file_names(&root.join("crates"))?
        .into_iter()
        .filter(|c| root.join("crates").join(c).join("Cargo.toml").is_file())
        .count();
    for (file, before, after) in [
        ("docs/README.md", "each of the ", " crates"),
        ("docs/dev/architecture.md", "workspace with ", " crates"),
    ] {
        let text = read(file)?;
        match number_between(&text, before, after) {
            Some(n) if n == crates => {}
            Some(n) => problems.push(format!("{file}: says {n} crates, but crates/ has {crates}")),
            None => problems.push(format!(
                "{file}: no crate count (\"{before}N{after}\") found"
            )),
        }
    }

    // The guides.
    for name in file_names(&root.join("docs"))? {
        if !name.ends_with(".md") || name == "README.md" {
            continue;
        }
        let text = read(&format!("docs/{name}"))?;
        if !GENERATED.contains(&name.as_str()) {
            let last = text.lines().rev().find(|l| l.starts_with("## "));
            if last != Some("## See also") {
                problems.push(format!(
                    "docs/{name}: does not end with a \"See also\" section"
                ));
            }
        }
        if !docs_index.contains(&format!("]({name})"))
            && !docs_index.contains(&format!("]({name}#"))
        {
            problems.push(format!("docs/{name}: not linked from docs/README.md"));
        }
    }
    Ok(problems)
}

/// The file names in `dir`, sorted.
fn file_names(dir: &Path) -> anyhow::Result<Vec<String>> {
    let mut out: Vec<String> = std::fs::read_dir(dir)
        .with_context(|| format!("listing {}", dir.display()))?
        .filter_map(Result::ok)
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    out.sort();
    Ok(out)
}

/// 17 for `0017-writers.md`.
fn adr_number(name: &str) -> Option<u32> {
    let (num, rest) = name.split_once('-')?;
    (num.len() == 4 && rest.ends_with(".md"))
        .then(|| num.parse().ok())
        .flatten()
}

/// The text from the heading `heading` to the next level-2 heading.
fn section<'a>(text: &'a str, heading: &str) -> &'a str {
    let Some(start) = text.find(&format!("\n{heading}\n")) else {
        return "";
    };
    let body = &text[start + heading.len() + 2..];
    match body.find("\n## ") {
        Some(end) => &body[..end],
        None => body,
    }
}

/// The ADRs a list links to, in order: the number the link text gives, and
/// the file it links to (with `prefix` removed).
fn adr_links(text: &str, prefix: &str) -> Vec<(u32, String)> {
    let mut out = Vec::new();
    for line in text.lines() {
        let Some(rest) = line.strip_prefix("- [ADR-") else {
            continue;
        };
        let Some(n) = rest.get(..4).and_then(|d| d.parse().ok()) else {
            continue;
        };
        let target = line
            .split_once("](")
            .and_then(|(_, t)| t.split_once(')'))
            .map(|(t, _)| t.strip_prefix(prefix).unwrap_or(t).to_owned())
            .unwrap_or_default();
        out.push((n, target));
    }
    out
}

fn compare_adr_list(
    what: &str,
    listed: &[(u32, String)],
    files: &[(u32, String)],
    problems: &mut Vec<String>,
) {
    for (n, name) in files {
        match listed.iter().filter(|(m, _)| m == n).count() {
            0 => problems.push(format!("{what}: ADR-{n:04} ({name}) is missing")),
            1 => {}
            k => problems.push(format!("{what}: ADR-{n:04} is listed {k} times")),
        }
    }
    for (n, target) in listed {
        match files.iter().find(|(m, _)| m == n) {
            None => problems.push(format!("{what}: ADR-{n:04} has no file in docs/adr")),
            Some((_, name)) if name != target => problems.push(format!(
                "{what}: ADR-{n:04} links to {target}, but the file is {name}"
            )),
            Some(_) => {}
        }
    }
    for pair in listed.windows(2) {
        if pair[1].0 < pair[0].0 {
            problems.push(format!(
                "{what}: ADR-{:04} comes after ADR-{:04}; list them in number order",
                pair[1].0, pair[0].0
            ));
        }
    }
}

/// The number written between `before` and `after`, such as 33 in
/// "each of the 33 crates".
fn number_between(text: &str, before: &str, after: &str) -> Option<usize> {
    text.match_indices(before).find_map(|(i, _)| {
        let rest = &text[i + before.len()..];
        let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
        (!digits.is_empty() && rest[digits.len()..].starts_with(after))
            .then(|| digits.parse().ok())
            .flatten()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_docs_are_current() {
        let problems = check(&root()).expect("the docs are readable");
        assert!(problems.is_empty(), "{}", problems.join("\n"));
    }

    #[test]
    fn adr_lists_are_compared() {
        let files = vec![(1, "0001-a.md".to_owned()), (2, "0002-b.md".to_owned())];
        let mut p = Vec::new();
        compare_adr_list(
            "index",
            &[(2, "0002-b.md".into()), (1, "0001-x.md".into())],
            &files,
            &mut p,
        );
        assert_eq!(
            p,
            vec![
                "index: ADR-0001 links to 0001-x.md, but the file is 0001-a.md",
                "index: ADR-0001 comes after ADR-0002; list them in number order",
            ]
        );
        let mut p = Vec::new();
        compare_adr_list("index", &[(1, "0001-a.md".into())], &files, &mut p);
        assert_eq!(p, vec!["index: ADR-0002 (0002-b.md) is missing"]);
    }

    #[test]
    fn numbers_and_links_are_read() {
        assert_eq!(adr_number("0017-writers.md"), Some(17));
        assert_eq!(adr_number("README.md"), None);
        assert_eq!(
            number_between("what each of the 33 crates does", "each of the ", " crates"),
            Some(33)
        );
        assert_eq!(
            adr_links("- [ADR-0017: Writers](adr/0017-writers.md): text", "adr/"),
            vec![(17, "0017-writers.md".to_owned())]
        );
        assert_eq!(
            section("a\n## Decisions\nx\ny\n## Next\nz", "## Decisions"),
            "x\ny"
        );
    }
}
