//! `cargo xtask notices [--check]`: writes `THIRD-PARTY-NOTICES.md`.
//!
//! The file has three parts:
//!
//! 1. The data files textweaver bundles (fonts, word lists, dictionaries,
//!    citation styles, font metrics): `about/data-files.md`, written by
//!    hand.
//! 2. The licences of those data files, copied verbatim from
//!    `third_party/` (the SCOWL copyright, each font's `OFL.txt`, and the
//!    WordNet and CMUdict notices, and LAME's LGPL).
//! 3. The Rust crates and their licences, generated by `cargo about` from
//!    `about.toml` and `about/crates.hbs`.
//!
//! `--check` regenerates it in memory and fails when the committed file
//! differs (line endings aside). Both need `cargo-about`
//! (`cargo install --locked cargo-about`).

use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, bail};

/// The notices file, relative to the root; `cargo xtask dist` packages it.
pub const NOTICES: &str = "THIRD-PARTY-NOTICES.md";

/// Licence files of bundled data, copied verbatim into the notices and into
/// every package: (source, heading).
pub const DATA_LICENCES: [(&str, &str); 7] = [
    (
        "third_party/scowl/Copyright",
        "SCOWL (spelling word levels)",
    ),
    (
        "third_party/fonts/atkinson-hyperlegible-next/OFL.txt",
        "Atkinson Hyperlegible Next",
    ),
    (
        "third_party/fonts/atkinson-hyperlegible-mono/OFL.txt",
        "Atkinson Hyperlegible Mono",
    ),
    ("third_party/fonts/opendyslexic/OFL.txt", "OpenDyslexic"),
    (
        "third_party/lexicon/WORDNET-LICENSE",
        "Open English WordNet (define word)",
    ),
    (
        "third_party/lexicon/CMUDICT-LICENSE",
        "CMUdict (define word pronunciations)",
    ),
    (
        "third_party/lame/COPYING",
        "LAME (MP3 export): GNU Library General Public License, version 2",
    ),
];

/// The hand-written part.
const DATA_FILES: &str = "about/data-files.md";
/// The `cargo about` configuration and template.
const ABOUT_CONFIG: &str = "about.toml";
const ABOUT_TEMPLATE: &str = "about/crates.hbs";

/// `cargo xtask notices`.
pub fn run() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(2).collect();
    let check = match args.as_slice() {
        [] => false,
        [a] if a == "--check" => true,
        _ => bail!("usage: cargo xtask notices [--check]"),
    };
    let root = crate::eci::root();
    let crates = cargo_about(&root)?;
    let text = compose(&root, &crates)?;
    let path = root.join(NOTICES);
    if check {
        let current =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        if normalized(&current) != text {
            bail!("{NOTICES} is out of date; run `cargo xtask notices`");
        }
        println!("{NOTICES} is up to date");
        return Ok(());
    }
    fs::write(&path, &text).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote {} ({} bytes)", path.display(), text.len());
    Ok(())
}

/// Line endings do not matter (upstream licence files use CR LF, and git
/// may check files out either way).
fn normalized(s: &str) -> String {
    s.replace("\r\n", "\n")
}

/// Runs `cargo about generate` and returns the crates section.
fn cargo_about(root: &Path) -> anyhow::Result<String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let out = Command::new(cargo)
        .current_dir(root)
        .args([
            "about",
            "generate",
            "--locked",
            "--all-features",
            "--fail",
            "-c",
            ABOUT_CONFIG,
            ABOUT_TEMPLATE,
        ])
        .output()
        .context("running cargo about (install it with `cargo install --locked cargo-about`)")?;
    if !out.status.success() {
        bail!(
            "cargo about failed (install it with `cargo install --locked cargo-about`):\n{}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    let text = String::from_utf8(out.stdout).context("cargo about wrote non-UTF-8 output")?;
    Ok(normalized(&text))
}

/// The whole notices file.
fn compose(root: &Path, crates: &str) -> anyhow::Result<String> {
    let data = fs::read_to_string(root.join(DATA_FILES))
        .with_context(|| format!("reading {DATA_FILES}"))?;
    let mut out = String::new();
    out.push_str(normalized(&data).trim_end());
    out.push_str("\n\n## Data file licences\n\nThese are copied unchanged from `third_party/`.\n");
    for (src, heading) in DATA_LICENCES {
        let text = fs::read_to_string(root.join(src)).with_context(|| format!("reading {src}"))?;
        out.push_str(&format!(
            "\n### {heading}\n\nFrom `{src}`.\n\n```text\n{}\n```\n",
            normalized(&text).trim_end()
        ));
    }
    out.push('\n');
    out.push_str(crates.trim_end());
    out.push('\n');
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inputs_exist() {
        let root = crate::eci::root();
        for f in [DATA_FILES, ABOUT_CONFIG, ABOUT_TEMPLATE, NOTICES] {
            assert!(root.join(f).is_file(), "{f} is missing");
        }
        for (src, _) in DATA_LICENCES {
            assert!(root.join(src).is_file(), "{src} is missing");
        }
    }

    #[test]
    fn the_notices_carry_every_data_licence() {
        let root = crate::eci::root();
        let notices = normalized(&fs::read_to_string(root.join(NOTICES)).unwrap());
        // The hand-written part is current.
        let data = normalized(&fs::read_to_string(root.join(DATA_FILES)).unwrap());
        assert!(
            notices.starts_with(data.trim_end()),
            "{NOTICES} does not start with {DATA_FILES}; run `cargo xtask notices`"
        );
        for (src, _) in DATA_LICENCES {
            let text = normalized(&fs::read_to_string(root.join(src)).unwrap());
            assert!(
                notices.contains(text.trim_end()),
                "{NOTICES} lacks {src}; run `cargo xtask notices`"
            );
        }
        for needle in [
            "Adobe Systems has no responsibility or obligation to support the use of the AFM files.",
            "CC BY-SA 3.0",
            "CC0",
            "## Rust crates",
        ] {
            assert!(notices.contains(needle), "{NOTICES} lacks {needle:?}");
        }
    }

    #[test]
    fn compose_puts_the_parts_in_order() {
        let root = crate::eci::root();
        let text = compose(&root, "## Rust crates\n\nnone\n").unwrap();
        let data = text.find("## Data file licences").unwrap();
        let crates = text.find("## Rust crates").unwrap();
        assert!(data < crates);
        assert!(!text.contains('\r'));
        assert!(text.ends_with("none\n"));
    }
}
