//! `cargo xtask notices [--check]`: writes `THIRD-PARTY-NOTICES.md`.
//!
//! The file has three parts, under its title and the copyright line from
//! `NOTICE`:
//!
//! 1. The data files textweaver bundles (fonts, word lists, dictionaries,
//!    citation styles, font metrics): `about/data-files.md`, written by
//!    hand.
//! 2. The licences of those data files, copied verbatim from
//!    `third_party/` (the SCOWL copyright, each font's `OFL.txt`, and the
//!    WordNet and CMUdict notices, and LAME's LGPL).
//! 3. The Rust crates and their licences, generated by `cargo about` from
//!    `about.toml` and `about/crates.hbs`.
//!
//! `--check` regenerates it in memory and fails when the committed file
//! differs (line endings aside). Both need `cargo-about`
//! (`cargo install --locked cargo-about`).

use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, bail};

/// The notices file, relative to the root; `cargo xtask dist` packages it.
pub const NOTICES: &str = "THIRD-PARTY-NOTICES.md";

/// Licence files of bundled data, copied verbatim into the notices and into
/// every package: (source, heading).
pub const DATA_LICENCES: [(&str, &str); 8] = [
    (
        "third_party/scowl/Copyright",
        "SCOWL (spelling word levels)",
    ),
    (
        "third_party/fonts/atkinson-hyperlegible-next/OFL.txt",
        "Atkinson Hyperlegible Next",
    ),
    (
        "third_party/fonts/atkinson-hyperlegible-mono/OFL.txt",
        "Atkinson Hyperlegible Mono",
    ),
    ("third_party/fonts/opendyslexic/OFL.txt", "OpenDyslexic"),
    (
        "third_party/fonts/lexend/OFL.txt",
        "Lexend (downloaded when chosen)",
    ),
    (
        "third_party/lexicon/WORDNET-LICENSE",
        "Open English WordNet (define word)",
    ),
    (
        "third_party/lexicon/CMUDICT-LICENSE",
        "CMUdict (define word pronunciations)",
    ),
    (
        "third_party/lame/COPYING",
        "LAME (MP3 export): GNU Library General Public License, version 2",
    ),
];

/// The hand-written part.
const DATA_FILES: &str = "about/data-files.md";
/// textweaver's own copyright notice; its first line heads the notices.
pub const NOTICE: &str = "NOTICE";
/// The `cargo about` configuration and template.
const ABOUT_CONFIG: &str = "about.toml";
const ABOUT_TEMPLATE: &str = "about/crates.hbs";

/// `cargo xtask notices`.
pub fn run() -> anyhow::Result<()> {
    let args: Vec<String> = std::env::args().skip(2).collect();
    let check = match args.as_slice() {
        [] => false,
        [a] if a == "--check" => true,
        _ => bail!("usage: cargo xtask notices [--check]"),
    };
    let root = crate::eci::root();
    if check {
        if !is_current(&root)? {
            bail!("{NOTICES} is out of date; run `cargo xtask notices`");
        }
        println!("{NOTICES} is up to date");
        return Ok(());
    }
    write(&root)
}

/// Whether the committed notices match what `cargo about` and the data
/// licence files give now (line endings aside).
pub fn is_current(root: &Path) -> anyhow::Result<bool> {
    let crates = cargo_about(root)?;
    let text = compose(root, &crates)?;
    let path = root.join(NOTICES);
    let current =
        fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    Ok(normalized(&current) == text)
}

/// Writes the notices file.
pub fn write(root: &Path) -> anyhow::Result<()> {
    let crates = cargo_about(root)?;
    let text = compose(root, &crates)?;
    let path = root.join(NOTICES);
    fs::write(&path, &text).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote {} ({} bytes)", path.display(), text.len());
    Ok(())
}

/// Whether `cargo about` is installed.
pub fn cargo_about_installed() -> bool {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    Command::new(cargo)
        .args(["about", "--version"])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

/// Line endings do not matter (upstream licence files use CR LF, and git
/// may check files out either way).
fn normalized(s: &str) -> String {
    s.replace("\r\n", "\n")
}

/// Runs `cargo about generate` and returns the crates section.
///
/// The output goes to a file in the target directory (`-o`), not a pipe:
/// cargo-about refuses to write to a redirected stdout when it runs under
/// PowerShell.
fn cargo_about(root: &Path) -> anyhow::Result<String> {
    let dir = crate::eci::target_dir(root).join("xtask-notices");
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    let file = dir.join("crates.md");
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let out = Command::new(cargo)
        .current_dir(root)
        .args([
            "about",
            "generate",
            "--locked",
            "--all-features",
            "--fail",
            "-c",
            ABOUT_CONFIG,
            "-o",
        ])
        .arg(&file)
        .arg(ABOUT_TEMPLATE)
        .output()
        .context("running cargo about (install it with `cargo install --locked cargo-about`)")?;
    if !out.status.success() {
        bail!(
            "cargo about failed (install it with `cargo install --locked cargo-about`):\n{}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    let text = fs::read(&file).with_context(|| format!("reading {}", file.display()))?;
    let text = String::from_utf8(text).context("cargo about wrote non-UTF-8 output")?;
    Ok(normalized(&text))
}

/// The hand-written part, with the copyright line (the first line of
/// [`NOTICE`]) under its title.
fn header(root: &Path) -> anyhow::Result<String> {
    let data = fs::read_to_string(root.join(DATA_FILES))
        .with_context(|| format!("reading {DATA_FILES}"))?;
    let notice =
        fs::read_to_string(root.join(NOTICE)).with_context(|| format!("reading {NOTICE}"))?;
    let copyright = notice.lines().next().unwrap_or_default().trim();
    let data = normalized(&data);
    let (title, rest) = data.split_once('\n').unwrap_or((data.as_str(), ""));
    Ok(format!("{title}\n\n{copyright}\n{}", rest.trim_end()))
}

/// The whole notices file.
fn compose(root: &Path, crates: &str) -> anyhow::Result<String> {
    let mut out = header(root)?;
    out.push_str("\n\n## Data file licences\n\nThese are copied unchanged from `third_party/`.\n");
    for (src, heading) in DATA_LICENCES {
        let text = fs::read_to_string(root.join(src)).with_context(|| format!("reading {src}"))?;
        out.push_str(&format!(
            "\n### {heading}\n\nFrom `{src}`.\n\n```text\n{}\n```\n",
            normalized(&text).trim_end()
        ));
    }
    out.push('\n');
    out.push_str(crates.trim_end());
    out.push('\n');
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inputs_exist() {
        let root = crate::eci::root();
        for f in [DATA_FILES, ABOUT_CONFIG, ABOUT_TEMPLATE, NOTICES, NOTICE] {
            assert!(root.join(f).is_file(), "{f} is missing");
        }
        for (src, _) in DATA_LICENCES {
            assert!(root.join(src).is_file(), "{src} is missing");
        }
    }

    #[test]
    fn the_notices_carry_every_data_licence() {
        let root = crate::eci::root();
        let notices = normalized(&fs::read_to_string(root.join(NOTICES)).unwrap());
        // The hand-written part and the copyright line are current.
        let header = header(&root).unwrap();
        assert!(
            notices.starts_with(&header),
            "{NOTICES} does not start with {DATA_FILES}; run `cargo xtask notices`"
        );
        for (src, _) in DATA_LICENCES {
            let text = normalized(&fs::read_to_string(root.join(src)).unwrap());
            assert!(
                notices.contains(text.trim_end()),
                "{NOTICES} lacks {src}; run `cargo xtask notices`"
            );
        }
        for needle in [
            "Adobe Systems has no responsibility or obligation to support the use of the AFM files.",
            "CC BY-SA 3.0",
            "CC0",
            "## Rust crates",
        ] {
            assert!(notices.contains(needle), "{NOTICES} lacks {needle:?}");
        }
    }

    #[test]
    fn compose_puts_the_parts_in_order() {
        let root = crate::eci::root();
        let text = compose(&root, "## Rust crates\n\nnone\n").unwrap();
        let data = text.find("## Data file licences").unwrap();
        let crates = text.find("## Rust crates").unwrap();
        assert!(data < crates);
        assert!(!text.contains('\r'));
        assert!(text.ends_with("none\n"));
        // The copyright line sits right under the title.
        let notice = fs::read_to_string(root.join(NOTICE)).unwrap();
        let second = text.lines().nth(2).unwrap();
        assert_eq!(Some(second), notice.lines().next());
        assert!(second.starts_with("Copyright (C) "));
    }
}
