#!/usr/bin/env python3
"""Generate the data and shared parts of the interactive pages in docs/site/.

The pages in docs/site/ are self-contained HTML files. They work when opened
straight from the file system, so every page carries its own copy of:

- the colour theme (CSS custom properties from the Galaxy and Galaxy Light
  theme files),
- the shared page styles, the skip link, the site header with its navigation
  and theme switch, and the shared script,
- its data, as JSON inside <script type="application/json" id="site-data">.

Each of those parts sits between marker comments such as
<!-- BEGIN generated: site-data --> and <!-- END generated: site-data -->.
This script rewrites only what is between the markers. Everything else in a
page is written by hand.

Where the data comes from:

- the crates: `cargo metadata --format-version 1 --no-deps`, plus the first
  paragraph of each crate's `//!` docs, plus the hand-kept ADR and layer
  tables below;
- the keys: docs/keyboard.md (generated by `cargo xtask keyboard`; never edit
  it) and the extra note keys in crates/textweaver-app/src/extra.rs;
- the colours: crates/textweaver-theme/themes/galaxy.toml and
  galaxy-light.toml;
- the features: the hand-kept FEATURES list below.

Usage (from anywhere; the script finds the repository root itself):

    python tools/gen_site_data.py           # rewrite the pages
    python tools/gen_site_data.py --check   # exit 1 if a page is stale

Python 3.11 or later, standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "docs" / "site"
DOCS = ROOT / "docs"

# ---------------------------------------------------------------------------
# Pages. The order here is the order of the site navigation.
# ---------------------------------------------------------------------------

PAGES = [
    # (file, link text in the navigation)
    ("index.html", "Home"),
    ("architecture.html", "Crate map"),
    ("speech-pipeline.html", "Speech pipeline"),
    ("keyboard.html", "Keyboard"),
    ("features.html", "Features"),
    ("reading-aids.html", "Reading aids"),
]

# ---------------------------------------------------------------------------
# Crates: owner ADRs. Hand-kept. Keys are crate names without the
# "textweaver-" prefix. An empty list means no ADR owns the crate.
# ---------------------------------------------------------------------------

CRATE_ADRS = {
    "core": ["0002", "0005"],
    "text": ["0002", "0005"],
    "formats": ["0010", "0002", "0026"],
    "ocr": ["0026"],
    "speech": ["0003", "0004", "0005"],
    "store": ["0001"],
    "keymap": ["0006"],
    "a11y": ["0006"],
    "editor": [],  # no ADR; the design is in plan section 6.6
    "app": ["0003", "0006", "0015"],
    "tui": ["0006", "0020", "0022"],
    "cli": ["0015", "0016", "0011"],
    "eci": ["0007", "0012"],
    "apple": ["0008"],
    "sapi": ["0009", "0012"],
    "enginehost": ["0012"],
    "export": ["0011"],
    "vault": [],
    "dictation": ["0013", "0023"],
    "gui": ["0014"],
    "xilem": ["0027"],
    "render": ["0016", "0018"],
    "convert": ["0016"],
    "writers": ["0017"],
    "math": ["0018"],
    "mathcat": ["0029", "0018"],
    "cite": ["0019"],
    "theme": ["0020"],
    "aids": ["0022", "0037"],
    "summary": ["0037"],
    "dectalk": ["0021", "0012"],
    "piper": ["0023", "0012"],
    "fonts": ["0017", "0022"],
    "lexicon": ["0025"],
    "engines": ["0001", "0012"],
    "xtask": ["0006", "0012"],
}

# Where to read about a crate that has no ADR: (link text, path from docs/site).
CRATE_NO_ADR_NOTE = {
    "editor": ("Architecture guide: the crates", "../dev/architecture.md#the-crates"),
}

# ---------------------------------------------------------------------------
# Crates: layers, for grouping the crate map. Hand-kept. The list order is the
# order of the map, top to bottom: the crates at the top depend on the ones
# below them.
# ---------------------------------------------------------------------------

LAYERS = [
    # (id, heading, one sentence, crates)
    ("tools", "Tools", "Maintenance tasks for developers; not part of the program.", ["xtask"]),
    ("frontends", "Frontends", "What you run: the terminal reader, the command-line tool, and the GUI.",
     ["tui", "cli", "gui", "xilem"]),
    ("application", "Application", "The application core that every frontend drives.", ["app"]),
    ("output", "Output and aids", "Writing other formats, and what changes how text looks.",
     ["render", "convert", "writers", "fonts", "theme", "aids", "summary", "lexicon", "vault", "dictation"]),
    ("state", "State and input", "Settings, saved positions, keys, announcements, and editing.",
     ["store", "keymap", "a11y", "editor"]),
    ("speech", "Speech", "The speech service, its backends, and audio export.",
     ["speech", "engines", "enginehost", "eci", "sapi", "apple", "dectalk", "piper", "export"]),
    ("document", "Document", "The document model and what loads, speaks, and cites it.",
     ["text", "formats", "ocr", "math", "mathcat", "cite"]),
    ("foundation", "Foundation", "Shared types that everything else builds on.", ["core"]),
]

# Crates that are tools rather than part of the program.
TOOL_CRATES = {"xtask"}

# A plainer one-sentence job where the first sentence of the crate docs is
# unclear or too long. Keys are short crate names.
JOB_OVERRIDES = {
    "core": "Shared leaf types: positions, units, offset maps, edits, and voice parameters.",
    "a11y": "Announces every state change, and routes it by the accessibility mode to speech, the status line, or both, so a screen reader never hears it twice.",
    "aids": "Reading aids: RSVP, bionic reading, the reading ruler, text spacing, reading level, syllables, and difficult words.",
    "summary": "Extractive summaries without a model: LexRank over the document's own sentences.",
    "apple": "Speaks with Apple's system voices on macOS, through the nsspeech and avspeech backends.",
    "cite": "Citations: a reference library, DOI and ISBN lookup, BibTeX, RIS, and CSL-JSON, and CSL styles.",
    "cli": "Builds tw, the scripting command-line tool: text, search, speak, convert, export audio, cite, serve, and more.",
    "convert": "Converts files and whole folder trees on all cores; the engine behind tw convert.",
    "dectalk": "Speaks with a DECtalk the user installed and licensed, through a separate host process.",
    "piper": "Speaks with Piper neural voices inside textweaver, on the pure-Rust RTen runtime, and finds, downloads, and checks the voices.",
    "dictation": "Voice typing: transcribes speech through a Whisper program and applies spoken commands.",
    "eci": "Speaks with ETI-Eloquence through the ECI library the user installed, in a separate host process.",
    "editor": "Editing: undo and redo over a rope, Markdown commands, typing echo, find and replace, and autosave.",
    "export": "Reads a document into audio and subtitle files: WAV, MP3, M4B with chapters, SRT, and WebVTT.",
    "fonts": "Bundled fonts (Atkinson Hyperlegible Next and Mono, OpenDyslexic), installed fonts found by family name, and the one place a font choice is resolved.",
    "engines": "The one speech engine registry every frontend shares: the built-in engines, Eloquence, SAPI5, Apple, and DECtalk, configured from the settings.",
    "formats": "Document loaders that turn text, Markdown, HTML, EPUB, DOCX, PDF (with OCR of scans), DAISY, PowerPoint, spreadsheets, archives, and web pages into a document.",
    "ocr": "Text recognition for scanned pages: the ocrs engine in process, Tesseract as a separate program, model downloads checked by SHA-256, and page images.",
    "gui": "The native GUI reader window on wxDragon; a feasibility spike, not built by default, kept as a fallback while Wave 3 builds the GUI on Xilem.",
    "xilem": "The all-Rust GUI on Masonry, Vello, Parley, AccessKit, and winit, with its own screen-reader document view; not built by default yet.",
    "keymap": "The keyboard vocabulary: every action, its default keys, layers, user overrides, and conflicts.",
    "lexicon": "Define word offline (your glossary, Open English WordNet, CMUdict pronunciations), and the message catalog for interface translations.",
    "math": "Math: LaTeX and ASCIIMath parsed into one tree, written as MathML, and spoken as natural English.",
    "sapi": "Speaks with Windows SAPI5 voices, each in a host process built for the voice's architecture.",
    "speech": "Speech backends and the speech service, with its own thread, queue, normalization, and word timing.",
    "store": "Persistence: settings (the reading-aid settings included), key overrides, per-document state with notes and highlights, recent files, and the library.",
    "vault": "Obsidian vault import and export for notes, highlights, and documents.",
    "xtask": "Maintenance tasks run with cargo xtask: keyboard.md, benchmarks and the soak test, engine hosts, release packages and the AppImage, the dependency check, licence notices, and the Star parity report.",
}

# ---------------------------------------------------------------------------
# Guides: link text for each guide the feature list links to.
# ---------------------------------------------------------------------------

GUIDE_TITLES = {
    "reading.md": "Reading and navigating guide",
    "notes.md": "Bookmarks, notes, and highlights guide",
    "keyboard.md": "Keyboard reference",
    "converting.md": "Converting documents guide",
    "star-gaps.md": "What Star did that textweaver does not do yet",
    "editing.md": "Editing guide",
    "citations.md": "Citations guide",
    "eloquence.md": "ETI-Eloquence guide",
    "speech.md": "Speech engines and voices guide",
    "dectalk.md": "DECtalk guide",
    "troubleshooting.md": "Troubleshooting guide",
    "math.md": "Math guide",
    "audio-export.md": "Audio export guide",
    "themes.md": "Themes guide",
    "reading-aids.md": "Reading aids guide",
    "library.md": "Library guide",
    "vault.md": "Obsidian vault guide",
    "dictation.md": "Dictation guide",
    "settings.md": "Settings guide",
    "json-rpc.md": "JSON-RPC server guide",
    "install.md": "Installation guide",
    "screen-readers.md": "Screen reader guide",
    "roadmap.md": "Roadmap",
    "gui.md": "The textweaver window (GUI)",
    "adr/0014-gui-toolkit.md": "ADR-0014: GUI toolkit (wxDragon)",
}

# ---------------------------------------------------------------------------
# Features for features.html. Hand-kept; statuses verified by the lead.
# Each entry: (name, one-sentence description, status, status note, guide).
# status is one of "done", "partial", "not yet". guide is a path in docs/.
# ---------------------------------------------------------------------------

FEATURES = [
    ("Reading", [
        ("Read aloud with exact word highlighting",
         "textweaver reads the document aloud and highlights each word as you hear it.",
         "done", "Works with every speech engine that reports word positions.", "reading.md"),
        ("Move by any unit",
         "Move by character, word, sentence, line, paragraph, heading, table, list, list item, link, or chapter.",
         "done", "Browse keys like NVDA's and JAWS's quick navigation, and chords, in both frontends.", "reading.md"),
        ("Speech Cursor line mode",
         "Read line by line with the arrow keys, like a screen reader's line review.",
         "done", "Press Tab in browse mode to turn it on or off.", "reading.md"),
        ("Find, go to, and navigation history",
         "Find text, go to a line or percentage, and go back to where you were before a jump.",
         "done", "Alt+Left goes back; Alt+Right goes forward again.", "reading.md"),
        ("Position restored on reopen",
         "Reopening a document puts you back where you stopped reading, even after the file changed in another program.",
         "done", "Saved in the background; your place, bookmarks, and notes are found again from their text.", "notes.md"),
        ("Tables, links, and footnotes",
         "Move by table row and cell with the column header, follow a link or footnote, and come back.",
         "done", "Ctrl+Alt+arrows in tables; Alt+Shift+F follows a link, wiki links included.", "reading.md"),
        ("Screen reader modes",
         "Choose who speaks: textweaver, your screen reader, or both, so nothing is heard twice.",
         "done", "Alt+Shift+A cycles self-voicing, hybrid, and screen reader.", "screen-readers.md"),
        ("Bookmarks, notes, and highlights",
         "Mark places, attach notes to words, and highlight passages, then list and step through them.",
         "done", "Saved per document.", "notes.md"),
        ("Command palette and keyboard help",
         "Run any command by name, and list every shortcut with your own changes applied.",
         "done", "F2 opens the palette; question mark lists the keys.", "keyboard.md"),
        ("Single-key shortcuts can be turned off",
         "Press F9 so that dictation or a switch keyboard never triggers a command by accident.",
         "done", "Chords, arrow keys, and the palette keep working.", "keyboard.md"),
    ]),
    ("Formats read", [
        ("Text, Markdown, HTML, EPUB, DOCX, and PDF",
         "Open these formats directly; Markdown includes GFM task lists, and PDF reading order follows columns.",
         "done", "Built in; nothing else to install.", "converting.md"),
        ("RTF and OpenDocument text, with comments and tracked changes",
         "RTF and ODT open directly, and comments in Word and ODT files become notes; tracked changes read as the final text or are said in place.",
         "done", "Built in; the reading setting revisions says changes.", "converting.md"),
        ("LaTeX, email, and saved web pages",
         "LaTeX with its sections, tables, math, references, and citations; email with its headers and attachments listed; and MHTML web archives, all without Pandoc.",
         "done", "Built in; LaTeX reads \\input files from its own folder only.", "converting.md"),
        ("Other formats through Pandoc",
         "reStructuredText, Org, and other formats convert through Pandoc in tw convert when Pandoc is installed.",
         "partial", "The reader itself does not use Pandoc: convert the file first.", "converting.md"),
        ("DAISY, PowerPoint, spreadsheets, archives, and web pages",
         "DAISY 3 books and Bookshare zips, slides with speaker notes, CSV and Excel as tables, zip, tar, and 7z archives, and web addresses.",
         "done", "Built in; web addresses open with tw.", "converting.md"),
        ("Scanned pages (OCR)",
         "Scanned PDFs and pictures are recognized: English in process with ocrs, other languages with Tesseract.",
         "done", "A one-time 12.2 MB model download (tw ocr download); Tesseract for other languages.", "converting.md"),
    ]),
    ("Writing", [
        ("Edit mode",
         "Write with typing echo, Markdown commands, undo, and find and replace.",
         "done", "Ctrl+E switches between reading and editing.", "editing.md"),
        ("Autosave recovery and changed-file warning",
         "Unsaved work is recovered after a crash, and you are warned when a file changed on disk.",
         "done", "Recovery is offered when you reopen the file.", "editing.md"),
        ("Citations in the editor",
         "Insert and format citations while writing.",
         "done", "Alt+C picks a reference; Alt+B (GUI Alt+Shift+D) adds one by DOI or ISBN; Alt+Shift+Q says citations while reading.", "citations.md"),
        ("Structure while writing and the outline",
         "Move by heading, list, link, and table in the text you are writing, and list the headings.",
         "done", "Alt+O lists the headings; type to filter them.", "editing.md"),
        ("Spell check",
         "Move to each misspelled word, hear it spelled, and choose a suggestion.",
         "done", "Alt+M and Alt+Shift+M; Alt+J for suggestions.", "editing.md"),
        ("Export and preview from the reader",
         "Export the document you are writing to PDF, Word, EPUB, braille, or a web page, and preview it in the browser.",
         "done", "From the command palette: export pdf, preview in browser.", "converting.md"),
        ("Templates",
         "Start a new document with front matter, today's date, and a References heading.",
         "done", "From the command palette: new from template.", "editing.md"),
        ("Copy, cut, and paste",
         "Copy to the system clipboard, and cut and paste while writing.",
         "done", "Ctrl+C copies through the terminal (OSC 52), over SSH too.", "editing.md"),
    ]),
    ("Speech", [
        ("ETI-Eloquence",
         "Use the ETI-Eloquence voices through the ECI library you installed.",
         "done", "Runs in its own host process.", "eloquence.md"),
        ("SAPI5 and OneCore voices on Windows",
         "Use the Windows voices, including 32-bit SAPI5 voices.",
         "done", "Each voice runs in a host process of the right architecture.", "speech.md"),
        ("Apple voices on macOS",
         "Use the macOS system voices through the nsspeech and avspeech backends.",
         "done", "Both backends report word positions.", "speech.md"),
        ("espeak-ng and speech-dispatcher on Linux",
         "Use espeak-ng directly, or any voice speech-dispatcher offers.",
         "done", "Available when installed.", "speech.md"),
        ("Omnivox",
         "Use the Omnivox speech server.",
         "done", "Highlighting is timer-paced, because Omnivox sends no word events.", "speech.md"),
        ("DECtalk",
         "Use a DECtalk you installed and licensed.",
         "partial", "Built and tested against a stand-in library, not yet against a licensed DECtalk.", "dectalk.md"),
        ("Choose a voice",
         "Pick a voice from a list while reading, with your favourites first.",
         "done", "Alt+V in the terminal; Space marks a favourite.", "speech.md"),
        ("Crash and stall recovery",
         "When a speech engine crashes or stops responding, textweaver restarts it and keeps your place.",
         "done", "Shift+F8 restarts speech at any time.", "troubleshooting.md"),
        ("Piper neural voices and a voice manager",
         "Download and use Piper voices, and manage every engine's voices in one list.",
         "done", "Alt+V in the terminal, Ctrl+Shift+V in the GUI; Piper voices download on request, with model-accurate word timing.", "speech.md"),
    ]),
    ("Math and citations", [
        ("Math read aloud",
         "Math is read in natural English, with the exact part highlighted as you hear it.",
         "done", "LaTeX and ASCIIMath in Markdown.", "math.md"),
        ("Math in converted documents",
         "LaTeX and ASCIIMath become MathML in HTML and EPUB, Word equations in DOCX, and typeset formulas in PDF.",
         "done", "Screen readers read MathML directly.", "math.md"),
        ("Explore math term by term in the reader",
         "Step through a formula term by term, into fractions and scripts.",
         "done", "Alt+Shift+X, then the arrow keys; Escape leaves.", "math.md"),
        ("Citations",
         "Look up references by DOI and ISBN, import and export BibTeX, RIS, and CSL-JSON, and format with CSL styles.",
         "done", "Through tw cite; tw convert adds a References section.", "citations.md"),
    ]),
    ("Output", [
        ("Convert documents",
         "tw convert writes Markdown, HTML, text, EPUB 3, DOCX, grade 1 braille (BRF), and tagged PDF.",
         "done", "Whole folders convert in parallel.", "converting.md"),
        ("Grade 2 braille",
         "Contracted braille output in BRF files.",
         "partial", "Needs the liblouis build feature and liblouis installed.", "converting.md"),
        ("Audio export",
         "Read a document into WAV, MP3, or M4B with chapters, plus SRT or WebVTT subtitles.",
         "done", "MP3 and M4B need ffmpeg.", "audio-export.md"),
    ]),
    ("Seeing the text", [
        ("Themes",
         "23 color themes with contrast checks, and your own themes.",
         "done", "F5 switches to the next theme.", "themes.md"),
        ("RSVP, bionic reading, ruler, spacing, and reading level",
         "Change how text looks: one word at a time, bold word starts, a reading ruler, wider spacing, and a reading level.",
         "done", "Try them on the reading aids page.", "reading-aids.md"),
        ("Difficult words and syllables",
         "Mark difficult words and show words split into syllables.",
         "done", "Alt+Shift+J and Alt+Shift+Z, in the terminal and the GUI.", "reading-aids.md"),
        ("Font choice",
         "Choose a reading font such as Atkinson Hyperlegible or OpenDyslexic.",
         "done", "In the GUI and HTML views; a terminal always uses its own font.", "reading-aids.md"),
    ]),
    ("Library and tools", [
        ("Library",
         "Library folders, recent files, sidecar sync, and full-text search.",
         "done", "Alt+L opens the library in the terminal.", "library.md"),
        ("Import from Star",
         "tw migrate-star brings over settings and reading positions from Star.",
         "done", "Run it once after installing.", "library.md"),
        ("Obsidian vault export and import",
         "Export notes and highlights to an Obsidian vault, and bring them back.",
         "done", "Through tw vault.", "vault.md"),
        ("Dictation from an audio file",
         "Transcribe a recording through a Whisper program.",
         "done", "Through tw dictate.", "dictation.md"),
        ("Dictation from the microphone",
         "Speak and have your words typed.",
         "partial", "Through tw dictate, with the in-process Whisper model; not yet from inside the reader.", "dictation.md"),
        ("Define a word",
         "Definitions, examples, synonyms, and pronunciation for the word at the cursor, from your glossary and Open English WordNet, offline.",
         "done", "Ctrl+Shift+D in the GUI, Alt+E in the terminal; tw define on the command line.", "reading.md"),
        ("Reading statistics",
         "Time read aloud, the furthest point, and sessions for each document, with a most-read list.",
         "done", "Ctrl+Shift+Y or Alt+Y; tw stats; off with [stats] enabled = false.", "reading.md"),
        ("Settings profiles",
         "Named sets of voice, rate, theme, font, spacing, highlight, and access mode to switch between.",
         "done", "Ctrl+Shift+U or Alt+U; tw settings profile.", "settings.md"),
        ("Interface translations",
         "textweaver's own words in other languages, with right-to-left support.",
         "done", "Six interface languages, including right-to-left layout.", "settings.md"),
        ("Settings export and import",
         "Save your settings and key changes as JSON, and load them on another computer.",
         "done", "Alt+Shift+E exports; Alt+Shift+I imports.", "settings.md"),
        ("JSON-RPC server",
         "tw serve --stdio lets other programs drive textweaver.",
         "done", "For scripting and add-ons.", "json-rpc.md"),
        ("Log file",
         "A log file records what went wrong, for troubleshooting.",
         "done", "The troubleshooting guide says where it is.", "troubleshooting.md"),
    ]),
    ("Platforms", [
        ("Windows and macOS release packages",
         "Download a package and run it.",
         "done", "Built by the release workflow.", "install.md"),
        ("Linux install script",
         "Build and install from source with one script, or install a release.",
         "done", "Building from source needs Rust; the script installs it after asking.", "install.md"),
        ("Linux AppImage",
         "One file that runs on most Linux distributions from 2022 on, with a plain tarball as a fallback.",
         "partial", "Built by the release workflow; the first release with it is the one after 0.1.0-alpha.3.", "install.md"),
        ("Native GUI on Xilem",
         "A native window for people who prefer a GUI, in the all-Rust Xilem toolkit with AccessKit.",
         "done", "Runs on Windows, macOS, and Linux, and ships with every release.", "gui.md"),
    ]),
]

STATUSES = ("done", "partial", "not yet")

# ---------------------------------------------------------------------------
# Keyboard: layer names as keyboard.md writes them, mapped to the ids the
# page uses. A key without a note is global.
# ---------------------------------------------------------------------------

LAYER_IDS = {"browse": "browse", "speech cursor": "speech_cursor", "edit": "edit", "global": "global"}

# The extra note keys in crates/textweaver-app/src/extra.rs: NoteCommand
# variant -> action description. The keys themselves are read from the file.
EXTRA_ACTIONS = {
    "Next": "Move to the next note",
    "Previous": "Move to the previous note",
    "ListHighlights": "List highlights",
}

# ---------------------------------------------------------------------------
# Theme colours: which theme-file entries become which CSS custom properties.
# ---------------------------------------------------------------------------

THEME_VARS = [
    # (CSS name, TOML table, key, sub-key or None)
    ("--bg", "colors", "background", None),
    ("--surface", "colors", "surface", None),
    ("--text", "colors", "text", None),
    ("--dim", "colors", "dim_text", None),
    ("--accent", "colors", "link", None),
    ("--h1", "colors", "heading1", None),
    ("--h2", "colors", "heading2", None),
    ("--h3", "colors", "heading3", None),
    ("--ok", "colors", "heading4", None),
    ("--code", "colors", "code", None),
    ("--error", "colors", "error", None),
    ("--mark-fg", "styles", "spoken_word", "foreground"),
    ("--mark-bg", "styles", "spoken_word", "background"),
    ("--sel-bg", "styles", "selection", "background"),
    ("--focus-fg", "styles", "focus", "foreground"),
]


class SiteError(Exception):
    """A problem the user can fix; printed without a traceback."""


# ---------------------------------------------------------------------------
# Crates
# ---------------------------------------------------------------------------


def short_name(name: str) -> str:
    return name[len("textweaver-"):] if name.startswith("textweaver-") else name


def run_cargo_metadata() -> dict:
    cargo = shutil.which("cargo")
    if cargo is None:
        raise SiteError(
            "cargo was not found. Install Rust from https://rustup.rs, "
            "or run this script from a shell where the cargo command works."
        )
    try:
        out = subprocess.run(
            [cargo, "metadata", "--format-version", "1", "--no-deps"],
            cwd=ROOT, capture_output=True, text=True, encoding="utf-8", check=False,
        )
    except OSError as e:
        raise SiteError(f"cargo could not be started: {e}") from e
    if out.returncode != 0:
        raise SiteError("cargo metadata failed:\n" + out.stderr.strip())
    return json.loads(out.stdout)


def clean_doc_text(s: str) -> str:
    """Strip rustdoc link syntax, backticks, emphasis, and ADR references."""
    s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)       # [text](target)
    s = re.sub(r"\[([^\]]+)\]", r"\1", s)                # [`Item`]
    s = s.replace("`", "")
    s = re.sub(r"\*\*([^*]+)\*\*", r"\1", s)
    s = re.sub(r"\s*\((?:ADR-\d{4}(?:,\s*)?)+\)", "", s)  # (ADR-0003, ADR-0004)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def first_sentence(text: str) -> str:
    m = re.search(r"(?<=[.!?])\s+(?=[A-Z])", text)
    sentence = text[: m.start()] if m else text
    sentence = sentence.strip()
    if sentence.endswith(":"):
        sentence = sentence[:-1] + "."
    if sentence and sentence[-1] not in ".!?":
        sentence += "."
    return sentence


def crate_doc_paragraph(pkg_dir: Path) -> str:
    for rel in ("src/lib.rs", "src/main.rs"):
        path = pkg_dir / rel
        if path.is_file():
            lines = []
            for line in path.read_text(encoding="utf-8").splitlines():
                if not line.startswith("//!"):
                    if lines:
                        break
                    continue
                body = line[3:].strip()
                if not body:
                    if lines:
                        break
                    continue
                lines.append(body)
            return " ".join(lines)
    return ""


def adr_index() -> dict:
    adrs = {}
    for path in sorted((DOCS / "adr").glob("[0-9][0-9][0-9][0-9]-*.md")):
        num = path.name[:4]
        title = path.stem
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                title = line[2:].strip().replace("`", "")
                break
        adrs[num] = {"number": num, "title": title, "href": f"../adr/{path.name}"}
    return adrs


def collect_crates() -> dict:
    meta = run_cargo_metadata()
    packages = meta["packages"]
    names = {p["name"] for p in packages}
    default_ids = set(meta.get("workspace_default_members") or [])
    adrs = adr_index()
    layer_of = {}
    for layer_id, _heading, _about, members in LAYERS:
        for c in members:
            layer_of[c] = layer_id

    crates = {}
    for p in packages:
        name = p["name"]
        short = short_name(name)
        deps = {"normal": set(), "build": set(), "dev": set()}
        for d in p["dependencies"]:
            if d["name"] in names:
                deps[d.get("kind") or "normal"].add(d["name"])
        pkg_dir = Path(p["manifest_path"]).parent
        job = JOB_OVERRIDES.get(short) or first_sentence(clean_doc_text(crate_doc_paragraph(pkg_dir)))
        if short not in CRATE_ADRS:
            raise SiteError(f"{name} is not in the CRATE_ADRS table in {Path(__file__).name}; add it.")
        if short not in layer_of:
            raise SiteError(f"{name} is not in the LAYERS table in {Path(__file__).name}; add it.")
        crate_adrs = []
        for num in CRATE_ADRS[short]:
            if num not in adrs:
                raise SiteError(f"ADR {num} for {name} has no file in docs/adr/.")
            crate_adrs.append(adrs[num])
        note = CRATE_NO_ADR_NOTE.get(short)
        try:
            rel_path = pkg_dir.resolve().relative_to(ROOT.resolve()).as_posix()
        except ValueError:
            rel_path = pkg_dir.as_posix()
        crates[name] = {
            "name": name,
            "short": short,
            "version": p["version"],
            "description": p.get("description") or "",
            "path": rel_path,
            "job": job,
            "layer": layer_of[short],
            "tool": short in TOOL_CRATES,
            "default_member": (p["id"] in default_ids) if default_ids else True,
            "bins": sorted(t["name"] for t in p["targets"] if "bin" in t["kind"]),
            "deps": sorted(deps["normal"]),
            "build_deps": sorted(deps["build"]),
            "dev_deps": sorted(deps["dev"] - deps["normal"]),
            "dependents": [],
            "adrs": crate_adrs,
            "adr_note": {"text": note[0], "href": note[1]} if note else None,
        }
    for name, c in crates.items():
        for d in c["deps"]:
            crates[d]["dependents"].append(name)
    for c in crates.values():
        c["dependents"].sort()

    order = []
    for _layer_id, _h, _a, members in LAYERS:
        for short in members:
            full = short if short in crates else f"textweaver-{short}"
            if full in crates:
                order.append(full)
    missing = set(crates) - set(order)
    if missing:
        raise SiteError("Crates missing from the LAYERS table: " + ", ".join(sorted(missing)))
    return {
        "crates": [crates[n] for n in order],
        "layers": [
            {"id": lid, "name": heading, "about": about,
             "crates": [n if n in crates else f"textweaver-{n}" for n in members
                        if (n in crates or f"textweaver-{n}" in crates)]}
            for lid, heading, about, members in LAYERS
        ],
    }


# ---------------------------------------------------------------------------
# Keyboard
# ---------------------------------------------------------------------------

KEY_RE = re.compile(r"(`+) ?(.+?) ?\1(?: \(([a-z ]+)\))?")


def parse_keys(cell: str) -> list:
    keys = []
    for m in KEY_RE.finditer(cell):
        layer = m.group(3) or "global"
        if layer not in LAYER_IDS:
            raise SiteError(f"docs/keyboard.md: unknown layer {layer!r} in {cell!r}")
        keys.append({"key": m.group(2), "layer": LAYER_IDS[layer]})
    return keys


def split_row(line: str) -> list:
    inner = line.strip()
    if inner.startswith("|"):
        inner = inner[1:]
    if inner.endswith("|"):
        inner = inner[:-1]
    return [c.strip() for c in inner.split(" | ")]


def collect_keys() -> dict:
    path = DOCS / "keyboard.md"
    if not path.is_file():
        raise SiteError("docs/keyboard.md is missing; run cargo xtask keyboard.")
    entries = []
    by_id = {}
    categories = []
    palette_rows = {}
    category = None
    in_table = False
    palette_section = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            category = line[3:].strip()
            in_table = False
            palette_section = category.lower().startswith("command palette only")
            continue
        if not line.startswith("|"):
            in_table = False
            continue
        cells = split_row(line)
        if cells[:4] == ["Action", "Terminal", "GUI", "Id"] or cells == [
            "Action", "Terminal", "GUI", "GUI on macOS", "Id"
        ]:
            in_table = True
            continue
        if not in_table or set(line.replace("|", "").strip()) <= set("-: "):
            continue
        if len(cells) == 5:
            action, term, gui, mac, ident = cells
        elif len(cells) == 4:
            action, term, gui, ident = cells
            mac = None
        else:
            raise SiteError(f"docs/keyboard.md: cannot read the row {line!r}")
        ident = ident.strip("`")
        if palette_section:
            palette_rows[ident] = {
                "terminal": term.strip() == "palette",
                "gui": gui.strip() == "palette",
            }
            continue
        if category not in categories:
            categories.append(category)
        entry = {
            "id": ident,
            "category": category,
            "action": action,
            "terminal": parse_keys(term),
            "gui": parse_keys(gui),
            "mac": parse_keys(mac.replace("Option+", "Alt+")) if mac is not None else None,
            "palette_when_off": None,
            "source": "keymap",
        }
        entries.append(entry)
        by_id[ident] = entry
    for ident, flags in palette_rows.items():
        if ident not in by_id:
            raise SiteError(f"docs/keyboard.md: palette row {ident!r} has no action row.")
        by_id[ident]["palette_when_off"] = flags

    # The extra note keys from the app.
    extra_path = ROOT / "crates" / "textweaver-app" / "src" / "extra.rs"
    text = extra_path.read_text(encoding="utf-8")
    found = re.findall(r'\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*NoteCommand::(\w+)\s*\)', text)
    if not found:
        raise SiteError("No extra bindings found in crates/textweaver-app/src/extra.rs.")
    extra_category = "Bookmarks and notes"
    for raw_key, variant in found:
        key = raw_key.encode("utf-8").decode("unicode_escape")
        keys = [{"key": key, "layer": "browse"}]
        entries.append({
            "id": f"NoteCommand::{variant}",
            "category": extra_category if extra_category in categories else categories[-1],
            "action": EXTRA_ACTIONS.get(variant, variant),
            "terminal": keys,
            "gui": [dict(k) for k in keys],
            "palette_when_off": None,
            "source": "extra",
        })
    return {"keys": entries, "categories": categories}


# ---------------------------------------------------------------------------
# Themes
# ---------------------------------------------------------------------------


def load_theme(name: str) -> dict:
    path = ROOT / "crates" / "textweaver-theme" / "themes" / f"{name}.toml"
    with path.open("rb") as f:
        data = tomllib.load(f)
    out = {}
    for css, table, key, sub in THEME_VARS:
        value = data[table][key]
        if sub:
            value = value[sub]
        out[css] = value
    return out


def theme_css(dark: dict, light: dict) -> str:
    def block(vals: dict, indent: str) -> str:
        return "\n".join(f"{indent}{k}: {v};" for k, v in vals.items())

    return (
        "/* Galaxy (dark, the default) and Galaxy Light, from\n"
        "   crates/textweaver-theme/themes/galaxy.toml and galaxy-light.toml. */\n"
        ":root {\n" + block(dark, "  ") + "\n  --border: var(--dim);\n  color-scheme: dark;\n}\n"
        "@media (prefers-color-scheme: light) {\n"
        "  :root:not([data-theme=\"dark\"]) {\n" + block(light, "    ") + "\n    color-scheme: light;\n  }\n}\n"
        ":root[data-theme=\"light\"] {\n" + block(light, "  ") + "\n  color-scheme: light;\n}\n"
    )


# ---------------------------------------------------------------------------
# Shared page parts
# ---------------------------------------------------------------------------

BASE_CSS = r"""
*, *::before, *::after { box-sizing: border-box; }
html { background: var(--bg); color: var(--text); }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: "Atkinson Hyperlegible Next", "Atkinson Hyperlegible", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif;
  font-size: 1.125rem;
  line-height: 1.6;
  overflow-wrap: break-word;
}
.wrap { max-width: 72rem; margin: 0 auto; padding: 0 1rem; }
h1, h2, h3, h4 { line-height: 1.25; margin: 1.5em 0 0.5em; }
h1 { color: var(--h1); font-size: 2.1rem; margin-top: 0.75em; }
h2 { color: var(--h2); font-size: 1.6rem; }
h3 { color: var(--text); font-size: 1.25rem; }
p, ul, ol, dl { margin: 0 0 1em; }
a { color: var(--accent); text-decoration: underline; text-underline-offset: 0.15em; }
a:hover { text-decoration-thickness: 0.15em; }
code, kbd {
  font-family: "Atkinson Hyperlegible Mono", ui-monospace, "Cascadia Mono", Consolas, Menlo, monospace;
  font-size: 0.95em;
  color: var(--code);
}
kbd { border: 1px solid var(--border); border-radius: 0.25em; padding: 0 0.25em; color: var(--text); white-space: nowrap; }
:focus-visible { outline: 3px solid var(--accent); outline-offset: 3px; }
.vh {
  position: absolute !important; width: 1px; height: 1px; padding: 0; margin: -1px;
  overflow: hidden; clip: rect(0 0 0 0); clip-path: inset(50%); white-space: nowrap; border: 0;
}
.skip-link {
  position: absolute; left: 0.5rem; top: -100rem; z-index: 10;
  background: var(--bg); color: var(--accent); padding: 0.5rem 1rem;
  border: 2px solid var(--accent); font-weight: bold;
}
.skip-link:focus { top: 0.5rem; }
.site-header { border-bottom: 2px solid var(--border); padding: 0.5rem 0 0.75rem; }
.site-header .wrap { display: flex; flex-wrap: wrap; align-items: center; gap: 0.5rem 1.5rem; }
.site-name { margin: 0; font-weight: bold; font-size: 1.25rem; }
.site-nav ul { list-style: none; margin: 0; padding: 0; display: flex; flex-wrap: wrap; gap: 0.25rem 0.5rem; }
.site-nav a { display: inline-block; padding: 0.4rem 0.5rem; min-height: 2.75rem; line-height: 1.9rem; }
.site-nav a[aria-current="page"] { color: var(--text); font-weight: bold; text-decoration-thickness: 0.2em; border-bottom: 3px solid var(--accent); }
.theme-switch { display: flex; flex-wrap: wrap; align-items: center; gap: 0.5rem; margin-left: auto; }
main { display: block; padding-bottom: 2rem; }
.site-footer { border-top: 2px solid var(--border); padding: 1rem 0 2rem; }
.site-footer h2 { font-size: 1.25rem; margin-top: 0.5em; }
button, select, input, textarea { font: inherit; color: var(--text); }
button, select, input[type="search"], input[type="number"], input[type="text"] {
  background: var(--surface);
  border: 2px solid var(--border);
  border-radius: 0.3rem;
  min-height: 2.75rem;
  padding: 0.3rem 0.75rem;
}
button { cursor: pointer; }
button:hover { border-color: var(--accent); }
input[type="range"] { accent-color: var(--accent); min-height: 2.75rem; min-width: 12rem; max-width: 100%; }
input[type="checkbox"], input[type="radio"] { accent-color: var(--accent); width: 1.5rem; height: 1.5rem; margin: 0 0.5rem 0 0; vertical-align: middle; }
fieldset { border: 2px solid var(--border); border-radius: 0.3rem; margin: 0 0 1rem; padding: 0.5rem 1rem 0.75rem; min-width: 0; }
legend { font-weight: bold; padding: 0 0.25rem; }
label { cursor: pointer; }
.check { display: flex; align-items: center; min-height: 2.75rem; }
.row { display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: center; margin: 0 0 1rem; }
.field { display: flex; flex-direction: column; gap: 0.25rem; margin: 0 0 1rem; max-width: 100%; }
.panel { background: var(--surface); border: 2px solid var(--border); border-radius: 0.4rem; padding: 0.5rem 1rem 1rem; margin: 0 0 1.5rem; }
.panel h2:first-child, .panel h3:first-child { margin-top: 0.5em; }
.status-line { border-left: 6px solid var(--accent); padding: 0.25rem 0.75rem; margin: 0 0 1rem; min-height: 2.5rem; }
.note { border-left: 6px double var(--border); padding: 0.25rem 0.75rem; }
.table-wrap { max-width: 100%; overflow-x: auto; margin: 0 0 1.5rem; }
table { border-collapse: collapse; width: 100%; }
caption { text-align: left; font-weight: bold; padding: 0.5rem 0; color: var(--text); }
th, td { border: 1px solid var(--border); padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; }
thead th { background: var(--surface); }
td code, th code { overflow-wrap: break-word; }
mark { background: var(--mark-bg); color: var(--mark-fg); }
@media (prefers-reduced-motion: no-preference) {
  html { scroll-behavior: smooth; }
}
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { animation: none !important; transition: none !important; scroll-behavior: auto !important; }
}
@media (forced-colors: active) {
  :focus-visible { outline: 3px solid Highlight; }
  button, select, input, fieldset, th, td, .panel, kbd { border-color: CanvasText; }
  .site-nav a[aria-current="page"] { border-bottom-color: Highlight; }
  .status-line, .note { border-left-color: CanvasText; }
}
@media print {
  .site-header, .skip-link, .theme-switch { display: none; }
}
""".strip("\n")

THEME_INIT_JS = (
    "<script>(function () {\n"
    "  try {\n"
    "    var t = window.localStorage.getItem(\"tw-site-theme\");\n"
    "    if (t === \"dark\" || t === \"light\") { document.documentElement.setAttribute(\"data-theme\", t); }\n"
    "  } catch (e) { /* storage blocked: follow the system setting */ }\n"
    "})();</script>"
)

BASE_JS = r"""
<script>
/* Shared by every page: data, announcements, theme switch. */
window.TW = (function () {
  "use strict";
  var data = {};
  try { data = JSON.parse(document.getElementById("site-data").textContent); } catch (e) { data = {}; }
  var statusEl = document.getElementById("status");
  var pending = null;
  /* Replace the text of the page's one live region. Repeating the same text
     clears it first, so screen readers announce it again. */
  function announce(message) {
    if (!statusEl) { return; }
    window.clearTimeout(pending);
    if (statusEl.textContent === message) {
      statusEl.textContent = "";
      pending = window.setTimeout(function () { statusEl.textContent = message; }, 100);
    } else {
      statusEl.textContent = message;
    }
  }
  function debounce(fn, ms) {
    var t = null;
    return function () {
      var args = arguments, self = this;
      window.clearTimeout(t);
      t = window.setTimeout(function () { fn.apply(self, args); }, ms);
    };
  }
  function plural(n, one, many) { return n + " " + (n === 1 ? one : many); }
  var KEY = "tw-site-theme";
  var root = document.documentElement;
  var select = document.getElementById("theme-select");
  function currentTheme() {
    var t = root.getAttribute("data-theme");
    return (t === "dark" || t === "light") ? t : "system";
  }
  if (select) {
    select.value = currentTheme();
    select.addEventListener("change", function () {
      var v = select.value;
      if (v === "dark" || v === "light") { root.setAttribute("data-theme", v); } else { root.removeAttribute("data-theme"); }
      try {
        if (v === "dark" || v === "light") { window.localStorage.setItem(KEY, v); } else { window.localStorage.removeItem(KEY); }
      } catch (e) { /* storage blocked: the choice lasts until the page closes */ }
    });
  }
  /* A table wider than the screen scrolls inside its box. Only then is the
     box a labelled region that Tab can reach, so the arrow keys can scroll
     it; otherwise it is a plain box and adds no tab stop. */
  function fitTables() {
    Array.prototype.forEach.call(document.querySelectorAll(".table-wrap"), function (w) {
      var label = w.getAttribute("aria-labelledby") || w.getAttribute("data-labelledby");
      if (label) { w.setAttribute("data-labelledby", label); }
      if (w.scrollWidth > w.clientWidth + 1) {
        w.setAttribute("role", "region");
        w.setAttribute("tabindex", "0");
        if (label) { w.setAttribute("aria-labelledby", label); }
      } else {
        w.removeAttribute("role");
        w.removeAttribute("tabindex");
        w.removeAttribute("aria-labelledby");
      }
    });
  }
  window.addEventListener("resize", debounce(fitTables, 200));
  window.addEventListener("load", fitTables);
  return { data: data, announce: announce, debounce: debounce, plural: plural, fitTables: fitTables };
})();
</script>
""".strip("\n")


def header_html(current: str) -> str:
    items = []
    for file, label in PAGES:
        cur = ' aria-current="page"' if file == current else ""
        items.append(f'        <li><a href="{file}"{cur}>{label}</a></li>')
    return (
        '<a class="skip-link" href="#main">Skip to main content</a>\n'
        '<header class="site-header">\n'
        '  <div class="wrap">\n'
        '    <p class="site-name">textweaver guide</p>\n'
        '    <nav class="site-nav" aria-label="Site">\n'
        '      <ul>\n' + "\n".join(items) + "\n"
        '      </ul>\n'
        '    </nav>\n'
        '    <div class="theme-switch">\n'
        '      <label for="theme-select">Color theme</label>\n'
        '      <select id="theme-select">\n'
        '        <option value="system">System</option>\n'
        '        <option value="dark">Dark (Galaxy)</option>\n'
        '        <option value="light">Light (Galaxy Light)</option>\n'
        '      </select>\n'
        '    </div>\n'
        '  </div>\n'
        '</header>'
    )


def json_script(data: dict) -> str:
    text = json.dumps(data, ensure_ascii=False, sort_keys=True, indent=1)
    text = text.replace("</", "<\\/").replace("<!--", "\\u003c!--")
    return f'<script type="application/json" id="site-data">\n{text}\n</script>'


# ---------------------------------------------------------------------------
# Page data
# ---------------------------------------------------------------------------


def features_data() -> dict:
    groups = []
    counts = {s: 0 for s in STATUSES}
    for group, items in FEATURES:
        out = []
        for name, desc, status, note, guide in items:
            if status not in STATUSES:
                raise SiteError(f"Feature {name!r} has an unknown status {status!r}.")
            if guide not in GUIDE_TITLES:
                raise SiteError(f"Feature {name!r} links to {guide}, which has no entry in GUIDE_TITLES.")
            counts[status] += 1
            out.append({
                "name": name, "description": desc, "status": status, "note": note,
                "guide": {"href": f"../{guide}", "title": GUIDE_TITLES[guide]},
            })
        groups.append({"name": group, "features": out})
    return {"groups": groups, "counts": counts, "total": sum(counts.values())}


def build_data() -> dict:
    """Everything the pages need, keyed by page file."""
    common = {
        "generator": "tools/gen_site_data.py",
        "pages": [{"file": f, "title": t} for f, t in PAGES],
    }
    crates = collect_crates()
    keys = collect_keys()
    feats = features_data()
    return {
        "index.html": {**common, "crate_count": len(crates["crates"]),
                       "key_count": len(keys["keys"]), "feature_counts": feats["counts"],
                       "feature_total": feats["total"]},
        "architecture.html": {**common, **crates},
        "speech-pipeline.html": {**common},
        "keyboard.html": {**common, **keys},
        "features.html": {**common, **feats},
        "reading-aids.html": {**common},
    }


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------


def replace_region(html: str, name: str, content: str, page: str) -> str:
    pattern = re.compile(
        r"(<!-- BEGIN generated: " + re.escape(name) + r" -->)(.*?)(<!-- END generated: "
        + re.escape(name) + r" -->)",
        re.DOTALL,
    )
    if not pattern.search(html):
        raise SiteError(f"docs/site/{page} has no '{name}' markers.")
    return pattern.sub(lambda m: m.group(1) + "\n" + content + "\n" + m.group(3), html, count=1)


def render_page(page: str, html: str, data: dict, css_vars: str) -> str:
    html = replace_region(html, "theme-init", THEME_INIT_JS, page)
    html = replace_region(html, "base-style", "<style>\n" + css_vars + BASE_CSS + "\n</style>", page)
    html = replace_region(html, "header", header_html(page), page)
    html = replace_region(html, "site-data", json_script(data), page)
    html = replace_region(html, "base-script", BASE_JS, page)
    return html


def main(argv: list | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the data in the docs/site/ pages.")
    parser.add_argument("--check", action="store_true",
                        help="change nothing; exit 1 and name the pages that are out of date")
    args = parser.parse_args(argv)
    try:
        data = build_data()
        css_vars = theme_css(load_theme("galaxy"), load_theme("galaxy-light"))
        stale = []
        for page, _title in PAGES:
            path = SITE / page
            if not path.is_file():
                raise SiteError(f"docs/site/{page} is missing.")
            old = path.read_text(encoding="utf-8")
            new = render_page(page, old, data[page], css_vars)
            if new == old:
                print(f"docs/site/{page} is up to date.")
            elif args.check:
                stale.append(page)
                print(f"docs/site/{page} is out of date.")
            else:
                path.write_text(new, encoding="utf-8", newline="\n")
                print(f"Wrote docs/site/{page}.")
    except SiteError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 2
    if stale:
        print("Run python tools/gen_site_data.py to update: " + ", ".join(stale) + ".", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
